### ISSUE TITLE
Add support to render markdown tables

### ISSUE THREAD

**Issue by hoghweed** [event-catalog/eventcatalog#1042]
### Use Case

Adding a markdown table within a markdown file (a service or whatever file) renders as text instead of a table.

The result is like the following image

![mk-table](https://github.com/user-attachments/assets/5aac55cd-02cf-4f43-9a31-a7a027ace6b6)

The table was added using the standard markdown format

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks @hoghweed this will be fixed in 2.18.5 (released 5min from this comment).

Thanks for the raising the issue
