### ISSUE TITLE
Side nav bar isn't sorted

### ISSUE THREAD

**Issue by ryancormack** [event-catalog/eventcatalog#1043]
### Use Case

The current Nav Sidebar isn't in a sorted order. It would be good if the events (for example) were either groups by Domain, or producer, and then sorted in alphabetical order. Or even just sorted in alphabetical order. In the screenshot, OrderCancelled and OrderConfirmed feel very much like they should be next to each other. It makes parsing the whole sidebar harder to find what you are looking for.

![image](https://github.com/user-attachments/assets/37f082cf-0db9-49a1-8807-396140f171c9)

### Proposed Solution

Order the side bar contents in alphabetical order

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks mate, these should now be sorted in 2.18.5 (released in the next 10min of this comment)
