### ISSUE TITLE
Order of versions is incorrect in services/messages view

### ISSUE THREAD

**Issue by jscheeres** [event-catalog/eventcatalog#1048]
### I tried this:

Check the latest version of Event and Service

### This happened:

![image](https://github.com/user-attachments/assets/3aae6276-0372-402a-ab25-faf4bfa90cb9)

Version 0.15.0 is the latest version. EventCatalog shows 0.2.1 as the latest version. In this case it's a Message. But the same issue occurs with Services.

### I expected this:

- v0.15.0 (latest)
- v0.2.1

### EventCatalog Version

2.17.3

### Node.js Version

node 22

### Platform(s)

Linux, Windows

**Comment by boyney123** [comment]
Thanks for raising this @jscheeres , will be fixed in 2.18.4 (releasing in the next 10 min of this post).
