### ISSUE TITLE
Ubiquitous Language not appearing

### ISSUE THREAD

**Issue by danieloldberg** [event-catalog/eventcatalog#1051]
### I tried this:

Suddenly the ubiquitous language sidebar component does not appear. Visiting /domains/<domain>/language present "This domain does not have any defined ubiquitous language terms yet. Consider adding some terms to help establish a common vocabulary for your domain.". The same if I'm running `npm run dev` and `npm run build && npm run start`.
Does not appear on a clean project using `npx @eventcatalog/create-eventcatalog@latest eventcatalog`.

### This happened:

Eventcatalog does not recognize any ubiquitous language defined. No error message anywhere.
In a clean installation, .eventcatalog-core/src/content/ubiquitousLanguages/domains/Orders/ubiquitous-language.mdx does exist. 

### I expected this:

For it to be available in the sidebar and the /language page.

### Is there a workaround?

Non I'm aware of.

### EventCatalog Version

@eventcatalog/core@2.18.1

### Node.js Version

v22.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks @danieloldberg , will take a look!

**Comment by boyney123** [comment]
Should be fixed in `2.18.2` just going out now , thanks for raising the issue

**Comment by danieloldberg** [comment]
Fantastic work on eventcatalog @boyney123 !

**Comment by boyney123** [comment]
Thank you 🙏 , any questions or problems let us know :), feel free to join us on Discord too if you ever fancy it
