### ISSUE TITLE
Support External Schema References

### ISSUE THREAD

**Issue by public-daniel** [event-catalog/eventcatalog#197]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Support external references within JSON schemas for events

### Motivation

This would be useful for events that share some common properties. For example, we have a "Timestamps" object that we attach to every event, and ideally we could reference an external (local) file instead of duplicating it into each individual event schema

**Comment by boyney123** [comment]
Hi @public-daniel,

Thank you for the idea/issue!

Yeah an interesting idea for sure, any thoughts on how it would work? I know you can use refs, are you using JSON Schema?

**Comment by StanClowes** [comment]
Hi

A really good example of this requirement is using CloudEvents with AsyncAPI
Here are a couple of examples where the CE spec is referenced: https://gist.github.com/lbroudoux/035ccc4d7b7cdd414f0ebc5a53e80c4c
https://microcks.io/blog/simulating-cloudevents-with-asyncapi/#structured-content-mode

We are using AsyncAPI/CloudEvents this way

**Comment by luke-gee** [comment]
As @StanClowes suggests. This feature would be extremely useful for cloud events adopters.

**Comment by boyney123** [comment]
Closing this issue.

EventCatalog v2 is being released, and no longer an issue.

If you still experience any of these issues, please raise a new ticket. 

Thank you!
