### ISSUE TITLE
Linking flows in visualizer

### ISSUE THREAD

**Issue by MartinWa** [event-catalog/eventcatalog#237]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

In the visualizer currently all services are shown as event-service-event and all events are shown as service-event-service but they are not linked. For example the [sample](https://app.eventcatalog.dev/visualiser/?type=all&name=AllEventsAndServices) has:
![image](https://user-images.githubusercontent.com/497015/157218051-182f93c5-09c3-4b94-b035-04ba67888013.png)

Could it be possible to enable a toggle (or something) in the visualizer that shows the flows like:
![image](https://user-images.githubusercontent.com/497015/157217673-887725f4-1e81-4e55-b813-c8463a942bf1.png)

If possible also allow recursions like:
![image](https://user-images.githubusercontent.com/497015/157218720-ab5a9d52-a6d7-4f51-8b5b-b9be00b69584.png)

### Motivation

I think it would be good to get a feel of the whole flow of events from start to end. Currently it is hard to get an overview of the whole system. Domains helped with the structuring but this part is missing to get the overall picture

**Comment by boyney123** [comment]
Going through issues now, and I'm marking this as an old issue.

Feel free to re-open if you want too and still think there is value here.

Thanks for spending the time opening in the first place, I appreciate it.
