### ISSUE TITLE
Bundle external resources to prevent render block

### ISSUE THREAD

**Issue by dytyniuk** [event-catalog/eventcatalog#300]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When a documentation website is built and deployed, sometimes external resources take forever to load. This leads to page render being blocked while waiting for these resources.

Primarily, this relates to the D3 resources loaded from the `unpkg.com`: `three.js` and `CSS2DRenderer.js`:
![Screenshot_2022-07-22_at_09 53 23](https://user-images.githubusercontent.com/1890615/183074181-0023a583-8c84-4697-a8cc-071b68ac9d7e.png)
![Screenshot_2022-07-22_at_10 36 48](https://user-images.githubusercontent.com/1890615/183074191-8a77c10f-9625-4d30-b9b1-b7de572a4821.png)

### Steps to reproduce

1. Build the website with `npm run build`
2. Open the website and check the _Network_ tab in your browser's Developer Tools

### Expected behavior

1. External resources are bundled when the website is built.
2. `script` tags are added to the bottom of the page's `body` to prevent render block.

### Actual behavior

1. `unpkg.com` resources rendered in the `head` of the page:
    ```html
    <head>
        <meta name="author" content="David Boyne"/>
        <meta name="next-head-count" content="15"/>
        <script src="//unpkg.com/three"></script>
        <script src="//unpkg.com/three/examples/js/renderers/CSS2DRenderer.js"></script>
        ...
        <script defer="" nomodule="" src="/event-catalog/_next/static/chunks/polyfills-0d1b80a048d4787e.js"></script>
        <script src="/event-catalog/_next/static/chunks/webpack-f3cfa8686900bcc2.js" defer=""></script>
        ...
    </head>
    ```
2. Page render is blocked until `unpkg.com` resources are loaded.

### Your environment

- `@eventcatalog/core` version used: `0.3.4`

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
