### ISSUE TITLE
Add documentation for plugin creation + boiler plate to get started

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#302]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Be great to add some docs around how people can write plugins and also some boiler code to help them get started.

EventCatalog supports two plugins at the moment, and users have expressed interest in creating more, but I believe that learning curve might be pretty high, having docs and boilerplate could help.

**Comment by davidcyp** [comment]
Same here. I was searching the website for more information on how to write plugins, it's only in this ticket that I've read that a plugin system indeed seems to exist. It would be interesting to leverage it more, put it in the spotlights. This way it would also become more interesting for the adoption of the project as I then can convince customers to use it since we have the flexibility to extend it.

**Comment by boyney123** [comment]
Thanks @bandantonio and @davidcyp , I'm going to start doing this, once I get the foundations for docs together, a review + test of them would be great! And any edits and additions would be a great support. 

Long term I would love a plugin gallery, would be epic! So many we can work towards that at some point.

**Comment by bandantonio** [comment]
@boyney123 I really like your ideas and we're on the same page about the final result we aim for. I'm sure that extensibility is exactly what people will love and what will make EventCatalog one of a kind! Can't wait to help you make these ideas real! 🤝

**Comment by davidcyp** [comment]
Make sure to ping on this thread for a review / test, I'll be watching It :)

**Comment by boyney123** [comment]
This is now live https://www.eventcatalog.dev/blog/eventcatalog-september-2024#plugin-generator-template,
