### ISSUE TITLE
Static site generation does not work - assets not loaded + routes rewrite path

### ISSUE THREAD

**Issue by jamesone** [event-catalog/eventcatalog#322]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When generating the static build `eventcatalog build` it does the following:

- out - Your EventCatalog as Static HTML (recommended to use)

However, when trying to view the index.html that is generated, no css/js is loaded 

Like seen in this photo: ![image](https://user-images.githubusercontent.com/12592075/200245265-d957d22b-1216-4789-81ec-1bf4e56ea3d3.png)

And the network tab shows this: 
![image](https://user-images.githubusercontent.com/12592075/200245424-a696a621-3a89-4f2a-a11a-263e8e29e1b1.png)

I want to host my event catalog on S3 as a static website, rather than requiring to host a next.js server.  

Also see that when I click on a link (to see my events), it will rewrite the path and not route to the desired page 

See the rewritten browser path: ![image](https://user-images.githubusercontent.com/12592075/200245832-ef5ff25c-2a0c-4f62-971f-a5e9ccbcabf6.png)

### Steps to reproduce

Create a new event catalog repo

1. yarn
2. yarn build
3. open `out/index.html` in chrome or desired browser
4. See that no assets are loading & when routing, it won't work

### Expected behavior

When building and opening the index.html, I would expect to see a fully functioning EventCatlog, including the ability to route to the different pages (i.e. to see my events, the visualiser, etc.)

### Actual behavior

When trying to view the index.html that is generated, no css/js is loaded 

Like seen in this photo: ![image](https://user-images.githubusercontent.com/12592075/200245265-d957d22b-1216-4789-81ec-1bf4e56ea3d3.png)

And the network tab shows this: 
![image](https://user-images.githubusercontent.com/12592075/200245424-a696a621-3a89-4f2a-a11a-263e8e29e1b1.png)

Also, see that when I click on a link (to see my events), it will rewrite the path and not route to the desired page 

See the rewritten browser path: ![image](https://user-images.githubusercontent.com/12592075/200245832-ef5ff25c-2a0c-4f62-971f-a5e9ccbcabf6.png)

### Your environment

- EventCatalog version used: `"@eventcatalog/core": "0.6.1"`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.4, Chrome 107.0.5304.87
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 12.3

**Comment by boyney123** [comment]
Hey, thanks for raising the issue @jamesone 

How are you running the content? Can you run serve it on your machine using something like https://www.npmjs.com/package/serve? If you run `npm serve` inside the folder then try it should work

**Comment by jamesone** [comment]
@boyney123 Oh, I was under the impression that this would work without needing a server. If that is the case, is the expectation that you host your static contents on S3 & then serve your other files via a server?

I was hoping it would just work within S3 - routing and all.

**Comment by jamesone** [comment]
To fix this issue, we'll need to support the nextjs `assetPrefix` configuration. This way I can set this to my S3 bucket URL and all local assets will have this prefixed. 

I am not sure if this fixes the href/link issue though. I'll hopefully get some time this week to look into this & maybe open a PR.

**Comment by batistein** [comment]
@jamesone any update on this topic? How did you manage to host a static site? I would be interested in running this on github pages...

**Comment by Brian-Azizi** [comment]
Any news on this. Hosting it as a static site does simply not work

**Comment by susliko** [comment]
@Brian-Azizi Hey 🖖🏻 
Were you able to open the static site locally? `.nojekyll` trick seems to have something with github pages only

**Comment by boyney123** [comment]
Seems a few folks having issues deploying the static site stuff, we have a few docs by the community to help here, maybe this can help a few of you. https://www.eventcatalog.dev/docs/guides/deployment#hosting-options

I haven't had the time to try various deployment places yet, so if anyone manages to get anything working would love to hear from you, and maybe we can get some docs updated on how you got it working, helping others too 🙏

**Comment by graegerts** [comment]
Hey David,

There definitely is an issue with static site generation as described in the OP.  Running `npm run build` creates HTML referencing resources with absolute paths.  For example (from `index.html`):

```html
<script src="/_next/static/chunks/main-369b70ec96aea56d.js" defer="">
```

That is not the expected result for a static build.  As I am by no means a FE developer I have no idea where to look to fix it.  Any help is appreciated.

**Comment by chinchala** [comment]
Any update on this topic?  Did anyone managed to host static files?

**Comment by mukuru-shaun** [comment]
Just a friendly bump on this.

Not supporting relative paths would be a deal breaker for a use-case I am investigating, so it would be nice to know if it is planned or not?

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!

---

We are moving to Astro from NextJS, hopefully this solves some issues too.
