### ISSUE TITLE
npm audit shows 16 high severity vulnerabilities

### ISSUE THREAD

**Issue by jethers** [event-catalog/eventcatalog#323]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When I installed eventcatalog npm got 16 high severity vulnerabilities.

### Steps to reproduce

1. Follow the steps in here and scaffold new project https://www.eventcatalog.dev/docs/installation
2. It shows 16 high severity vulnerabilities were found.

### Expected behavior

npm should not show any severity vulnerabilities.

### Actual behavior

[root@ip-172-31-89-108 eventcatalog]# npx @eventcatalog/create-eventcatalog@latest catalogo-eventos
Creating a new eventcatalog in /var/opt/eventcatalog/catalogo-eventos.

Installing dependencies:
- @eventcatalog/core

npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated react-flow-renderer@9.7.4: react-flow-renderer has been renamed to reactflow, please use this package from now on https://reactflow.dev/docs/guides/migrate-to-v11/

added 804 packages, and audited 805 packages in 50s

171 packages are looking for funding
  run `npm fund` for details

**16 high severity vulnerabilities**

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Installing devDependencies:
- @types/react
- @eventcatalog/types
- @types/node

added 11 packages, changed 1 package, and audited 816 packages in 6s

171 packages are looking for funding
  run `npm fund` for details

16 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Success! Created catalogo-eventos at /var/opt/eventcatalog/catalogo-eventos
Inside that directory, you can run several commands:

  npm run dev
    Starts the app in development mode.

  npm start
    Runs the app in production mode.

We suggest that you begin by typing:

  cd catalogo-eventos
  npm run dev

### Your environment

- EventCatalog version used: @eventcatalog/core@0.6.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 17.9.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Amazon Linux release 2 (Karoo)

**Comment by DanielRuf** [comment]
This is quite "normal". See also https://overreacted.io/npm-audit-broken-by-design/

Related: https://github.com/boyney123/eventcatalog/issues/276

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
