### ISSUE TITLE
Edit link is wrong for a service page in a domain

### ISSUE THREAD

**Issue by arturoabruzzini** [event-catalog/eventcatalog#324]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

If you have a service page inside a domain, like `/domains/MyDomain/services/MyService`, then the edit link on the service page will have the wrong path, it will link to `/services/MyService` instead.

### Steps to reproduce

- Create an EventCatalog with a domain, and a service inside that domain
- Click the Edit button on the service page

### Expected behavior

Just like for events that sit inside a domain, services that sit inside a domain should have a correct edit link with the domain in the path.

### Actual behavior

The edit link on a service page that's inside a domain links to a root level service, which won't work.

### Your environment

- EventCatalog version used: @eventcatalog/core 0.6.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): any
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): any

**Comment by boyney123** [comment]
Thank you @arturoabruzzini , fix incoming https://github.com/boyney123/eventcatalog/pull/336

**Comment by boyney123** [comment]
fixed and deployed :)
