### ISSUE TITLE
User definition

### ISSUE THREAD

**Issue by alimuhammadca** [event-catalog/eventcatalog#341]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It seems that user definitions are picked up from ./eventcatalog-core/eventcatalog.config.js rather than ./eventcatalog.config.js.  

### Steps to reproduce

Add a new user in ./eventcatalog.config.js
In a domain page add the user as an owner. 

### Expected behavior

Expected to see the user as an owner of the domain

### Actual behavior

No user is shown

### Your environment

- EventCatalog version used: 0.6.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 16.13.2, Chrome 108
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

**Comment by gaddam1987** [comment]
It is same for asycnapi generator with external schema files.  For the below example the `payload` refres to `abc.json`  and the async file is in the `EVENTLOG` home directory. So the expectation is that abc.json should also be in the same directory as the async api file but the generator fails with `ParserError: Error opening file "*/my-catalog/.eventcatalog-core/abc.json"`. 

`
asyncapi: 2.0.0
info:
  title: Email Service
  version: '1.0.0'
  description: |
    This service is responsible for managing user accounts in the system.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  production:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
    description: Test MQTT broker

channels:
  user/signedup:
    publish:
      operationId: onUserSignUp
      message:
        $ref : '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: 'abc.json'
        `

**Comment by boyney123** [comment]
@alimuhammadca thanks for raising the issue.

I just tried to replicate the issue, with no luck, here are my steps:

1. Install new EventCatalog `npx @eventcatalog/create-eventcatalog@latest my-catalog`
1. Added user to the `eventcatalog.config.js` file
1. Ran in dev mode and added user to domain, and the user was in the domain folder

Wonder if this is a windows issue though, @gaddam1987 are you using windows?

**Comment by gaddam1987** [comment]
The issue i am facing is not user config file its while using generator
Add this generator
```
[
      [
          '@eventcatalog/plugin-doc-generator-asyncapi',
          {
              pathToSpec: [path.join(__dirname, 'asyncapi-user-account.yml')],
              versionEvents: true,
              domainName: 'UserAccount'
          },
      ]
  ]
```

And the `asyncapi-user-account.yml` looks like this which is in directory my-catalog

```
asyncapi: 2.0.0
info:
  title: Account Service
  version: '1.0.0'
  description: |
    This service is responsible for managing user accounts in the system.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  production:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
    description: Test MQTT broker

channels:
  user/signedup:
    subscribe:
      operationId: emitUserSignUpEvent
      message:
        $ref : '#/components/messages/UserSignedUp'

components:
  messages:
    UserSignedUp:
      name: userSignedUp
      title: User signed up event
      summary: Inform about a new user registration in the system
      contentType: application/json
      payload:
        $ref: 'abc.json'
```

And also schema file `abc.json` is in the directory my-catalog and the content look slike this
```
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
```

The `npm run generate` fails saying there is no file named àbc.json` in directory `my-catalog/.eventcatalog-core/abc.json` because the file is in the home director of the project that is `my-catalog/abc.json`

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
