### ISSUE TITLE
Global full text search

### ISSUE THREAD

**Issue by nbrinks** [event-catalog/eventcatalog#365]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

A global full text search bar that can search across: domains, services, events, openapi, asyncapi, etc.

Probably not searching just names but also descriptions and any piece of documentation.

Tools like elasticlunr.js or lunr.js may be useful for this feature.

### Motivation

On larger architectures it would be nice to not necessarily have to understand the system as specific domains, services, events, etc. but have a flexible search tool that can be used to aid in discovery. It may not always be the case that users know the specific domain, service, event, etc. but they may understand something else about the domain context that hopefully can direct them to the applicable domain, service, event, etc. This of course would require providing enough documentation to begin with to make the search tool useful.

**Comment by fourhundredfour** [comment]
An option for this would be https://typesense.org

**Comment by boyney123** [comment]
This is now coming to EventCatalog v2! Soon to be released.
