### ISSUE TITLE
Eventbridge plug-in fails on archive events 

### ISSUE THREAD

**Issue by Muthuveerappanv** [event-catalog/eventcatalog#366]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

eventbridge plug-in generator fails when your event bus has a archive event/target in it. The error occurs due to a malformed arn which is being parsed through a cdk function

Archive  targets are usually like this ‘arn:aws:vhs-gamma-pod02:us-east-1:::’

### Steps to reproduce

1. Create a event archive in the eventbus
2. This will create a archival target like  ‘arn:aws:vhs-gamma-pod02:us-east-1:::’’
3. Run the eventbridge generator now 

### Expected behavior

All events , sources and targets are generated without issues

### Actual behavior

The event target fails when the arn is parser through the cdk function 

it fails the entire event generation process and ends abruptly

### Your environment

- EventCatalog version used: 0.6.8 , 0.0.10 (eventbridge plugin)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodejs 16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS

**Comment by boyney123** [comment]
Going through issues now, and I'm marking this as an old issue.

Feel free to re-open if you want too and still think there is value here.

Thanks for spending the time opening in the first place, I appreciate it.
