### ISSUE TITLE
Theme customization

### ISSUE THREAD

**Issue by thawankeane** [event-catalog/eventcatalog#377]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It will be nice if we can customize the theme (maybe through [tailwind theme configuration](https://tailwindcss.com/docs/theme)?)the 

### Motivation

Many teams and products have their own design system, if eventcatalog exposes tailwind configuration file those customizations could be done easily.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
