### ISSUE TITLE
missing yarn.lock in the scaffolding files

### ISSUE THREAD

**Issue by reza8iucs** [event-catalog/eventcatalog#379]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

In the [installation guide ](https://www.eventcatalog.dev/docs/installation) it's recommended to use Yarn as the package manager but all the build/run commands are in npm. Also, following the instructions, the scaffolding files are missing the yarn.lock file which will cause problems with GitHub actions when building the container as the dockerfile has references to yarn.lock.    

```
(https://github.com/UcsForestGroup/WiseEventCatalog/actions/runs/4657137589/jobs/8241435405#step:5:152)
buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref wpcq4rgx2lgl6cor41v9nb1ut::ufqq9a9u3ek03i8okv8srlzi5: "/yarn.lock": not found

```

### Steps to reproduce

Follow the inductions here https://www.eventcatalog.dev/docs/installation

### Expected behavior

update the installation doc to include the equivalent yarn commands instead of npm

### Actual behavior

npm commands are referenced. When they are used for building the project they conflict with yarn which is what CI/Cd pipeline expects to see artefacts such as yarn.lock for.

### Your environment

- EventCatalog version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
