### ISSUE TITLE
Normalise JSON Schema formatting before diffing in changelog

### ISSUE THREAD

**Issue by estahn** [event-catalog/eventcatalog#382]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Schema's sometimes may have different formatting. Before passing the schema to the "differ" they should be normalised/formatted to achieve the best result. This is probably up for discussion, whether this is being done automatically by `eventcatalog` or via CLI when adding the schema.

### Motivation

Simplify workflow.

### Example

| Current | Expected |
|---------|-------------|
| ![image](https://user-images.githubusercontent.com/362174/234794414-5f63f419-0af4-48a2-965c-cd9473e68b8e.png) | ![image](https://user-images.githubusercontent.com/362174/234794474-12d7d9eb-e4e8-4baf-9e33-d1a70d368f95.png) |

**Comment by boyney123** [comment]
Hey @estahn 

Interesting, do you have a screenshot of what is happening, and what you expect to happen, to help anyone who wants to pick this up.

**Comment by estahn** [comment]
@boyney123 I have added screenshots. I would assume running the schema through `JSON.stringify({ a:1, b:2, c:3 }, null, 4)` before diffing it would solve the issue.

**Comment by boyney123** [comment]
Going through issues now, and I'm marking this as an old issue.

Feel free to re-open if you want too and still think there is value here.

Thanks for spending the time opening in the first place, I appreciate it.
