### ISSUE TITLE
 AsyncAPI plugin generator: upgrade Parser from v1 to v2 and save and render AsyncAPI file in service page automatically

### ISSUE THREAD

**Issue by nchebbi** [event-catalog/eventcatalog#386]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Hello David,

I highly appreciate your efforts in making eventcatalog.

The idea is add the AsyncAPI component markdown to the service page and save the asyncapi yaml file processed by the asyncapi  plugin generator to service folder, the that file will be rendered in the service page automatically.

### Motivation

We are using eventcatalog and already made some changes to it locally, mainly created a new AsyncAPI pluging generator based the newly released AsyncAPI parser v 2.x.x and where we added a feature to add the AsyncAPI component markdown to the service page and save the asyncapi yaml file to the service folder so the service page will render the asyncapi.yml file.
There were some chnages needed in the eventcatalog/utils as well, I already created a PR (#385) to merge the changes.
If the idea is motivating for you let me know so I can copy the the required changes from my plugin to the asyncAPI plugin generator (upgrrading the AsyncAPI parser as well to v2.x.x) and create a PR for it. it will be somehow a re-write as the api has changed.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
