### ISSUE TITLE
Download Schema button for OpenAPI and AsyncAPI

### ISSUE THREAD

**Issue by kernwig** [event-catalog/eventcatalog#403]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

My JSON Schema pages have a nice "Download Schema" button, but OpenAPI services do not.
I assume AsyncAPI is also missing this and would benefit from the addition.

### Motivation

Someone in QA asked for the OpenAPI YAML, and I wanted to point her to download it from Event Catalog, but there's no button!

**Comment by kernwig** [comment]
I tried working around this with 
`[Download Schema](openapi.yaml)` - nope, it isn't actually deployed as a file.

Also tried duplicating `openapi.yaml` as `schema.yaml` and adding `<Schema/>` to the markdown, but this doesn't work on services.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
