### ISSUE TITLE
Ignore directories that start with dot or are "hidden"

### ISSUE THREAD

**Issue by kernwig** [event-catalog/eventcatalog#404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

In the services, events, and domain directories, Event Catalog processes each directory as a new service, event, or domain to process.
This processing picks up directories that start with a dot too, resulting in a fatal error in `eventcatalog dev` execution.

You may say "don't do that". But MacOS occasionally creates a `.DS_Store` directory for its own purposes. I believe I've seen this behavior in other operating systems. Linux uses dot to hide files and directories as well. Windows creates desktop and thumbnail files all over the place with a "hidden" file attribute.

### Steps to reproduce

1. Create a sub-directory under `services` without an `index.md` file.
2. Run `eventcatalog dev`
3. Navigate to localhost:3000/services

### Expected behavior

The non-service (event, domain) directory is ignored instead of crashing.

### Actual behavior

```
Server Error
Error: ENOTDIR: not a directory, open '<path>/services/nada/index.md'
```

### Your environment

- EventCatalog version used: 0.6.12
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 114 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

**Comment by kernwig** [comment]
Just realized that the "nada" example I made to get the error message for "Action behavior" is actually a file, not a directory. Skipping files would be a good idea too. I think that would handle the case of the Windows OS `Desktop.ini` file pollution, without having to access the hidden attribute on the file.

**Comment by kernwig** [comment]
Okay, I lean toward the solution of ignoring a directory without `index.md`, instead of erroring out.

I ran into a similar problem switching from a development branch where I had defined a new event, back to the main branch. Git removes my new index.md, but leaves the empty directory behind.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
