### ISSUE TITLE
[eventcatalog-plugin-generator-asyncapi] Switches producers and consumers

### ISSUE THREAD

**Issue by JoostvdB94** [event-catalog/eventcatalog#405]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When using AsyncAPI for generating the eventcatalog pages, the consumer and producer statements are switched.
When the asyncAPI states that an application produces an event, the generator will place that event in the "consumes" list.

This is either wildly confusing, or a bug.

### Steps to reproduce

1. Create an AsyncAPI document which states that an application produces an event. Or fetch the example in the plugin directory `src/examples/kafka.yml`
2.  Run the generation as described in the readme
3. See that a service document has been made that states that _Streetlights Kafka API_ consumes `lightMeasured`

### Expected behavior

I would expect that:

Publishers of an event (as defined in asyncapi) would show up as producers of an event
Subsribers to an event would show up as Consumers

### Actual behavior

Publishers of an event (as defined in asyncapi) show up as consumers of an event
Subsribers to an event show up as Producers

### Your environment

Windows 10
Node v18

**Comment by JoostvdB94** [comment]
After some more research, I've found that this is a longer running discussion.
Other templates have functionality to switch the viewpoint. (as mentioned by https://www.asyncapi.com/blog/publish-subscribe-semantics). Perhaps the PR should add this instead of switching the verbs

**Comment by susliko** [comment]
Also stumbled upon this 🤯

**Comment by boyney123** [comment]
Going through issues now, and I'm marking this as an old issue.

Feel free to re-open if you want too and still think there is value here.

Thanks for spending the time opening in the first place, I appreciate it.
