### ISSUE TITLE
Versioning of Services

### ISSUE THREAD

**Issue by susliko** [event-catalog/eventcatalog#424]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Adding an ability to version Services similarly to [Versioning Events](https://www.eventcatalog.dev/docs/events/versioning). It might have the same file structure with `versioned` directory and a similar interface

### Motivation

It's often important to document both "as is" and "to be" states of the system. For now the event catalog supports OpenAPI and AsyncAPI for services, but there is no clear way to reflect an evolution of its public interface (both api, published and subscribed events)

**Comment by boyney123** [comment]
This is coming to EventCatalog v2! Which is going to be released very soon, so closing this issue as a clean up job.
