### ISSUE TITLE
Use Mermaid components in domains

### ISSUE THREAD

**Issue by manuelspezzani** [event-catalog/eventcatalog#427]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

As far as I can tell, Mermaid components can render custom graphs but cannot be used in domains. 

```
<Mermaid title="Event Rules & Targets" charts={[`flowchart LR 
Start --> Stop`]} />
```

It would be really nice to have them also on domains pages.
Not sure what to do display as the default chart, probably it can be simply ignored (nothing is rendered).

### Motivation

I tend to use domain pages to describe the service / events architecture on a really high level.
Having the option to include a few Mermaid charts could be really helpful.

**Comment by stanipetrosyan** [comment]
Hi, I create Pull Request #407 for this. I'm waiting for approve.

**Comment by donaldpipowitch** [comment]
Hi @boyney123 , is there something that blocks a merge of https://github.com/boyney123/eventcatalog/pull/407? Could you maybe also update the mermaid dependency? (It seems to be a fixed version, but I don't know if this is on purpose.)

Right now there is no workaround that would allow us to import custom components on the fly, correct?

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

EventCatalog will support mermaid code blocks!

If you still experience this issue please raise a new issue. 

Thank you!
