### ISSUE TITLE
Version 2.6.0 is not supported

### ISSUE THREAD

**Issue by CyberHippo** [event-catalog/eventcatalog#441]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Not really a bug but the AsyncAPI version 2.6.0 is not yet supported. I think updating the `@asyncapi/parser` deps to [`v1.18.0`](https://github.com/asyncapi/parser-js/releases/tag/v1.18.0) in the plugin [`plugin-generator-asyncapi`](https://github.com/boyney123/eventcatalog/blob/master/packages/eventcatalog-plugin-generator-asyncapi/package.json#L22C6-L22C22) would allow parsing `2.6.0` asyncapi manifests. I'll try to open a PR to update the plugin dependency.

### Steps to reproduce

1. Have an asyncapi manifest in version `2.6.0`
2. Run `npm run generate`

You'll get the following error : 
```
ParserError: Version 2.6.0 is not supported.
```

### Expected behavior

I would expect the `generate` command to generate a catalog from my AsyncAPI files thanks to the plugin [`plugin-generator-asyncapi`](https://www.eventcatalog.dev/docs/api/plugins/@eventcatalog/plugin-doc-generator-asyncapi).

### Actual behavior

It fails with: 
```
ParserError: Version 2.6.0 is not supported.
```

### Your environment

- EventCatalog version used:
  -  `@asyncapi/bundler`: `0.3.11`
  -  `@eventcatalog/core`: `1.0.5`
  -  `@eventcatalog/plugin-doc-generator-asyncapi`: `0.3.5`

- Environment name and version (e.g. Chrome 89, Node.js 16.4): `Node.js v18.8.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): /

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!

**Comment by CyberHippo** [comment]
Excited for EventCatalog v2!
