### ISSUE TITLE
Issue in rendering mermaid diagram

### ISSUE THREAD

**Issue by RenugaParamalingam** [event-catalog/eventcatalog#466]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Mermaid diagrams are consistently collapsing, and this issue is not limited to a specific browser or a glitch. The official demo site too have this problem.

<img width="1498" alt="Screenshot 2023-12-18 at 3 22 25 PM" src="https://github.com/boyney123/eventcatalog/assets/39623765/3cef2d17-411b-4f2e-a5c9-06f39821ab18">

### Steps to reproduce

Download and install EventCatalog per the instructions. Run the EventCatalog in local machine. Navigate to events tab and click the `Show Mermaid Diagrams` check box in the filters panel on the left.
Or,
Check official demo site with `Show Mermaid Diagrams` check box ticked https://app.eventcatalog.dev/events/

### Expected behavior

Mermaid diagrams should show up without any issue.

### Actual behavior

Mermaid diagrams are getting collapsed.

### Your environment

- EventCatalog version used: 1.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 120.0.6099.109, Firefox 120.0.1 (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac 13.2.1

**Comment by 1bberto** [comment]
facing the same issue here
<img width="245" alt="image" src="https://github.com/boyney123/eventcatalog/assets/3129978/b4209078-22a3-48af-8e2f-49cc8fec42c6">

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
