### ISSUE TITLE
Overriding next.js config is for largePageDataBytes

### ISSUE THREAD

**Issue by jrodriguez5-fsl-godaddy** [event-catalog/eventcatalog#490]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

I am trying to override the standard next.config.js to be able to process larger openapi.yaml files but when I save the change and run the eventcatalog, my changes are automatically deleted.

### Steps to reproduce

1. Make a change in .eventcatalog-core within next.config.js
2. Save the change
3. run 'npm run dev'

### Expected behavior

I expect it to save my changes to be able to process larger files

### Actual behavior

It deletes the changes and runs the standard configuration.

### Your environment

- EventCatalog version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
