### ISSUE TITLE
Security vulnerability: Regular Expression Denial of Service in trim

### ISSUE THREAD

**Issue by trullarn** [event-catalog/eventcatalog#491]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

We have an audit right now and we need to resolve the issue of Event Catalog using an old version of "trim" through one of its dependencys

"Regular Expression Denial of Service in trim"

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
fix available via npm audit fix
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/@mdx-js/mdx/node_modules/remark-parse
  node_modules/remark-mdx/node_modules/remark-parse
    @mdx-js/mdx  <=1.6.22
    Depends on vulnerable versions of remark-mdx
    Depends on vulnerable versions of remark-parse
    node_modules/@mdx-js/mdx
      next-mdx-remote  <=3.0.8
      Depends on vulnerable versions of @mdx-js/mdx
      node_modules/next-mdx-remote
    remark-mdx  <=1.6.22
    Depends on vulnerable versions of remark-parse
    node_modules/remark-mdx

"npm autit fix" didnt fix it

It would seem that @mdx-js/react and next-mdx-remote needs to be updated to use a newer version of trim 

### Steps to reproduce

run "npm audit" to see the issue

### Expected behavior

No vulnerabilities :)

### Actual behavior

The repo uses an old version of the "trim" package which exposes it to vulnerabilities. 

### Your environment

- EventCatalog version used: 1.2.5
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 20
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

**Comment by trullarn** [comment]
Any ETA on this? 
There are probably more companies that needs this to be resolved when they do security audits =)

Thanks for a great product!

**Comment by jnixon2** [comment]
Any update on these vulnerabilities being patched at all?

**Comment by boyney123** [comment]
Thanks for the issue. Will try and get to this, unless you can try to update the packages and let us know how you get on. Happy to accept a PR too

**Comment by Inx51** [comment]
Any news regarding this? Sadly Im way to unfamiliar with the tools and libs used to build event-catalog, else I would gladly give it a shot to upgrade the required packages in a "safe way".. but would love to use ec to document our system, but the 7,5 cve-rating prevents me from doing that.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
