### ISSUE TITLE
Event Search clears when enter pressed

### ISSUE THREAD

**Issue by kernwig** [event-catalog/eventcatalog#493]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Pressing ENTER key in search box clears the search.

### Steps to reproduce

- Go to https://app.eventcatalog.dev/events
- Type "Item" into the search box.
- See that list of events limits down to just the events with the word Item in the name
- Press the enter key (because that's habit)

### Expected behavior

Nothing changes.

### Actual behavior

Page reloads with URL https://app.eventcatalog.dev/events/?event=Item, **every** event showing, and the search box cleared.

### Your environment

- EventCatalog version used: 1.1.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome v122
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.3.1

**Comment by boyney123** [comment]
Going through issues now, and I'm marking this as an old issue.

Feel free to re-open if you want too and still think there is value here.

Thanks for spending the time opening in the first place, I appreciate it.
