### ISSUE TITLE
Owners are being removed from domains index.md file

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#495]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

After running the command `npm run generate` the **owners** section is removed from the index.md for domain and services.

### Steps to reproduce

1. Add manually **owners** in the index.md file for any domain you have
2. Run the command `npm run generate`
3. Take a look at the index.md file for all domains and/or services, and you will see that the owners section was removed

### Expected behavior

The owners section must be kept in the `index.md`file of domain and services, even after running `npm run generate`

### Actual behavior

The owners section is being removed from the `index.md` for domains and services.

### Your environment

- EventCatalog version used: 1.2.5
- Environment name and version (e.g. Chrome 89, Node.js 16.4): NodeJS v21.6.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Sonoma

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
