### ISSUE TITLE
Data Lake 404's in the demo site

### ISSUE THREAD

**Issue by corbin-bloomerang** [event-catalog/eventcatalog#496]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When clicking on the `Data Lake` links in the [visualizer](https://app.eventcatalog.dev/visualiser/), I get sent to this page https://app.eventcatalog.dev/services/Data%20Lake with a 404 error. Other links to the Data Lake also 404.

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
