### ISSUE TITLE
content security policy need to have unsafe-eval to render the generated event page from AWS event bridge

### ISSUE THREAD

**Issue by wliew99** [event-catalog/eventcatalog#497]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Cannot render the generated events without granting **_unsafe-eval_** to the content security policy, which is very concerning as it opens up room for cross site scripting attack.
 

### Steps to reproduce

content security policy on CloudFront distribution to serve s3 static files build from event catalog have
_default-src https: wss: 'self'; style-src https: 'unsafe-inline'_

If i changed content security policy to _default-src https: wss: 'unsafe-eval'; style-src https: 'unsafe-inline'_ then everything is fine.

When drilling down to our generated event details page (from plugin generation from EB), getting this on client side
![image](https://github.com/boyney123/eventcatalog/assets/90648179/e1e0ef89-1b72-435b-baa1-d4939c811016)

F12 console gave this
![image](https://github.com/boyney123/eventcatalog/assets/90648179/fab699d0-8d32-4a0d-ab03-b8042b62b6e3)
![image](https://github.com/boyney123/eventcatalog/assets/90648179/c8b3ef52-dc59-4c72-9d8e-1322521f2adb)

### Expected behavior

the generated event page to be rendered with _default-src https: wss: 'self'; style-src https: 'unsafe-inline'_

### Actual behavior

got client side exception as it's looking for unsafe-eval to be part of CSP

### Your environment

- EventCatalog version used: 1.2.5
- Plugin generator against EB: ^0.0.12
- Environment name and version (e.g. Edge for Business 123.0 and Chrome 123.0, Node.js 18.19.1):
- Operating system and version (e.g. Ubuntu 22.04 LTS):

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
