### ISSUE TITLE
Search directly via the URL

### ISSUE THREAD

**Issue by marciovmartins** [event-catalog/eventcatalog#498]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Option to get a term searched via the URL, for example:
- https://app.eventcatalog.dev/events?q=Order
- https://app.eventcatalog.dev/services?q=Order
- https://app.eventcatalog.dev/domains?q=Order

This would already load the page with the "Search Events|Service|Domain" filled and the result filtered.

### Motivation

This would enable third-party tools to have shortcuts to directly search for the "Event" like CLI alias or Alfredapp.

```sh
# could open https://app.eventcatalog.dev/events?q=Order
sre Order
# could open https://app.eventcatalog.dev/services?q=Order
srs Order
# could open https://app.eventcatalog.dev/domains?q=Order
srd Order
```

Instead of open the Event Catalog in the web browser, click in the "Search Events" input box, fill the text and wait for the result to be queried.

**Comment by boyney123** [comment]
Yeah like the idea!

**Comment by boyney123** [comment]
EventCatalog will now have support for search in v2, will close this for now. Let me know if you still want this support or not in v2.
