### ISSUE TITLE
[plugin-doc-generator-amazon-eventbridge] customized parts get deleted on generate

### ISSUE THREAD

**Issue by hffmnn** [event-catalog/eventcatalog#500]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When re-generating events via the `plugin-doc-generator-amazon-eventbridge` plugin, customized parts of the markdown get deleted.

### Steps to reproduce

1. Edit parts of the automatically generated markdown, e.g.
```
// Parts automatically generated by the plugin
---
## Matched rules for event

// Manually added parts
---
## Details

Some more details...
```
2. Regenerate the docs with `npm run generate`

### Expected behavior

Manually added parts should still be there

```
// Manually added parts
---
## Details

Some more details...
```

### Actual behavior

Manually added parts are deleted

### Your environment

- EventCatalog version used:
```
"@eventcatalog/core": "1.2.5",
"@eventcatalog/plugin-doc-generator-amazon-eventbridge": "^0.0.12"
```

**Comment by s1mrankaur** [comment]
+1 same issue with plugin-generator-asyncapi

**Comment by bastiankoetsier** [comment]
+1

**Comment by MichaelBaumgarn** [comment]
+1
