### ISSUE TITLE
Undefined values when rendering SQS as targets in Amazon Event Bridge

### ISSUE THREAD

**Issue by danielcastill0** [event-catalog/eventcatalog#501]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

As the image below, getting 
<img width="702" alt="Screen Shot 2024-04-11 at 4 47 56 PM" src="https://github.com/boyney123/eventcatalog/assets/40574235/4c759c02-4209-4792-b8f3-ebed0d4cf9c0">

### Steps to reproduce

just build the documentation

### Expected behavior

<img width="649" alt="Screen Shot 2024-04-11 at 4 49 30 PM" src="https://github.com/boyney123/eventcatalog/assets/40574235/8a3e400c-618f-42e3-b3ca-d722b69d8b14">

### Actual behavior

I got the issue and I'd to collaborate withe resolution @boyney123 

### Your environment

    "@eventcatalog/core": "1.1.0",
    "@eventcatalog/plugin-doc-generator-amazon-eventbridge": "^0.0.12",
    "@eventcatalog/utils": "^0.2.2"

**Comment by boyney123** [comment]
Thanks for raising this. You mentioned on Discord about a fix, do you fancy try making a PR for it?

**Comment by danielcastill0** [comment]
@boyney123 this is the PR! https://github.com/boyney123/eventcatalog/pull/506

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
