### ISSUE TITLE
Link "Click on Visualiser" doesn't work when services are Open API specifications

### ISSUE THREAD

**Issue by imrafaelmerino** [event-catalog/eventcatalog#514]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Clicking on the button `View in Visualiser` returns an unhandled error

### Steps to reproduce

1. Create a service adding an Open API spec 
2. Go to http://localhost:3000/services/my-service/
3. Click on `View on Visualiser` button

### Expected behavior

Either not return an error or doesn't show the button

### Actual behavior

<img width="1008" alt="Captura de Pantalla 2024-04-25 a las 10 13 46" src="https://github.com/boyney123/eventcatalog/assets/52382610/82c4bfc7-46a5-47fc-8d59-1f8f08e2039c">

### Your environment

- EventCatalog version used: 1.2.7
- Environment name and version (e.g. Chrome 89, Node.js 16.4): any browser, node v21.7.3
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):  any OS

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
