### ISSUE TITLE
Infinite build loop when building without running dev first

### ISSUE THREAD

**Issue by Laupetin** [event-catalog/eventcatalog#532]
When trying to build EventCatalog using `npm run build` without running `npm run dev` first seems to result in an infinite loop trying to call the build script again.

![image](https://github.com/event-catalog/eventcatalog/assets/9197140/0adb139b-369c-4d40-83b1-b0fc55942ce6)

This can be replicated by deleting the `.eventcatalog-core` folder which is gitignored by default.

It can be solved by first running `npm run dev`, aborting and afterwards running `npm run build`.

For development on my local machine this isn't quite a big issue.
It just makes building EventCatalog with our CI a bit difficult.

**Comment by boyney123** [comment]
Thanks! Will take a look
