### ISSUE TITLE
Building EventCatalog does not seem to include content

### ISSUE THREAD

**Issue by Laupetin** [event-catalog/eventcatalog#541]
Running `npm run build` with a new demo event catalog setup does not seem to include content like services,events,domains,commands,...

Looking at the build log, the following is logged:
![image](https://github.com/event-catalog/eventcatalog/assets/9197140/78853514-4248-4de1-a9dc-8642e91f566f)

Running `npm run dev` seems to work fine however.

**Comment by boyney123** [comment]
Thanks! And thanks for the PR

Fixed in @eventcatalog/core@2.0.6
