### ISSUE TITLE
v2 schema rendering not scrollable vertically

### ISSUE THREAD

**Issue by wliew99** [event-catalog/eventcatalog#548]
# Summary
Have a relatively large schema.json in JSON schema format and using <Schema file="schema.json">  does not render the vertical scrolling but render the whole schema.json in the component.  The horizontal scrolling show up but not the vertical one .

# Expected Behavior
Limit the real estate (ability to set size?) of schema.json being shown on index.md by having both vertical and horizontal scrolling.

# Actual Behavior
The whole schema.json got render on index.md

**Comment by otbe** [comment]
I really liked the old SchemaViewer component :)

**Comment by boyney123** [comment]
Yeah I got some feedback also from others about SchemaViewer, so I'm going to add SchemaViewer back in!

**Comment by boyney123** [comment]
SchemaViewer back in, closing now :)
