### ISSUE TITLE
Receives Messages / Sends Messages displays ID instead of name

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#549]
# Summary

In the service detail page, the sections "Receives Messages" and  "Sends Messages" display the id of the message/event instead of the name.

# Expected Behavior

It should use the name instead of the ID.

# Actual Behavior

Displays the ID, see picture:
<img width="323" alt="Screenshot 2024-07-06 at 19 23 25" src="https://github.com/event-catalog/eventcatalog/assets/3391052/eecc6692-1c5a-4472-9c49-bbdd9cfc9433">

**Comment by boyney123** [comment]
Thanks for raising this @otbe , great to see you back too! been awhile :)

Fixed in `@eventcatalog/core:2.0.7`
