### ISSUE TITLE
Versions of a message/events are cut off if there are too many

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#551]
# Summary

If you have a lot of versions of one event they get cut off and you can scroll the whole area horizontally.

<img width="344" alt="Screenshot 2024-07-06 at 19 57 16" src="https://github.com/event-catalog/eventcatalog/assets/3391052/94104628-a24e-4e81-b48d-c7af12b8dce6">
<img width="262" alt="Screenshot 2024-07-06 at 19 58 20" src="https://github.com/event-catalog/eventcatalog/assets/3391052/4a28aec7-df90-4db9-b1fb-40aa0cf14bdf">

**Comment by boyney123** [comment]
Thanks for this, yeah seems an issue.

I'm wondering if after X versions we should change this to a dropdown? Any thoughts on that @otbe ?

**Comment by otbe** [comment]
Yeah that sounds like a good idea :)

**Comment by boyney123** [comment]
Should be live in `2.0.8` now :)
