### ISSUE TITLE
eventcatalog build fails with TS error if you have many objects

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#552]
# Summary

When trying to build the catalog via `eventcatalog build` it fails with the following TS error:

```
src/components/DocsNavigation.astro:19:17 - error ts(2590): Expression produces a union type that is too complex to represent.

19 const allData = [ ...domains, ...services, ...messages, ...teams, ...users];
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We work with 30 domains, 25 services and ~950 events. dev mode wokrs fine.

**Comment by boyney123** [comment]
Hmmm interesting one, I'm going to create a big catalog locally for this. 

Is it possible you could setup a fork of this big one at all? Saves me time building something massive, maybe ofc remove any PII information or sensitive info? Is that possible, or not? Let me know and I will have a look

**Comment by otbe** [comment]
I think this is not possible. Besides the events/services it also contains a lot of business process descriptions :)

**Comment by otbe** [comment]
I made some changes to be able to build it at least once locally see https://github.com/otbe/eventcatalog/tree/fix-ts-issues

However it turns out Im not able to finish the build. Node goes OOM even with `NODE_OPTIONS=--max-old-space-size=25000 ` (in v1 `--max-old-space-size=8192` was enough)

**Comment by otbe** [comment]
Finding from today. The error starts to popup as soon as I add services.
~950 events and 30 domains are no issues. When I add the services (without any links to each other) it starts to fail with the errors from above.

**Comment by otbe** [comment]
I opened a merge request. No idea why there are so many unrelated changes after formatting via "format" script but the real changes are

- https://github.com/event-catalog/eventcatalog/pull/593/files#diff-078a04af1bc179bb1b518949ad21649bb99ee4c1141d38377fe006d49b5b374eR20
- https://github.com/event-catalog/eventcatalog/pull/593/files#diff-078a04af1bc179bb1b518949ad21649bb99ee4c1141d38377fe006d49b5b374eR30
- https://github.com/event-catalog/eventcatalog/pull/593/files#diff-d8ba078e52be5d0d5dc084c84e44b02c5fd0d9dc93154a4c1e06118f7ec9a8a8R14

Without these 3 lines I cannot build the big catalog. Might be some TS voodoo.
