### ISSUE TITLE
Link to service from domain page does not include version -> 404

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#553]
# Summary

If you add a service to a domain and try to click on it you end up in a 404 page because the link itself does not contain the version.

So its `docs/services/foo-service` instead of `docs/services/foo-service/0.0.1` in my example.

<img width="335" alt="Screenshot 2024-07-07 at 10 33 33" src="https://github.com/event-catalog/eventcatalog/assets/3391052/eb2142c5-efc8-494b-89e0-e6c74098bc86">

**Comment by boyney123** [comment]
Thanks for raising!

Fixed in `@eventcatalog/core:2.0.7`
