### ISSUE TITLE
Allow to hide/disable certain areas in the left sidebar

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#556]
It would be nice if we can configure certain areas in the sidebar similar to 

```
{
  docs: {
    sidebar: {
      showPageHeadings: false,
    },
  },
}
```

Im thinking of disabling messages (events for now, commands/queries maybe later) completely because to display a list of >900 events in this way makes no sense really.

**Comment by boyney123** [comment]
Yeah I hear you, I'm tempted to add a filterable dropdown in that list to help... let me explore a few things, will get back to you. I have others also experiencing similar things.

**Comment by boyney123** [comment]
So this is my thinking at the moment.

- You can turn on filtering for each section in the nav
- You can set a max default rendered value

Demo
https://github.com/event-catalog/eventcatalog/assets/3268013/58c230dc-06e1-4db0-9a3f-7658ea09afb5

Thoughts? Would this help?

**Comment by otbe** [comment]
Wouldnt this be a bit redundant to the global search and the "Discover" section? 🤔
I think I would people redirect to the global search if they know what they are looking for or to discover section if they want to discover a domain/event/whatever.

**Comment by wliew99** [comment]
i like the discover page of events better.
I like to hide the service section on the main left menu, if made available.

**Comment by boyney123** [comment]
Cool, I added the ability to hide things in the navigation bar and configure it.

https://www.eventcatalog.dev/docs/api/config#docs

Just waiting for GitHub actions to unqueue my release, not sure what issues they are having at the moment. Once that's done new release will go out with this feature.

**Comment by boyney123** [comment]
OK this now out in 2.0.10. Will close this issue for now, thanks for raising
