### ISSUE TITLE
Multiline summary is displayed on a single line in the visualiser

### ISSUE THREAD

**Issue by debae** [event-catalog/eventcatalog#560]
### Summary
Multiline summary is displayed on a single line in the visualiser

#### Description
When using multiline markdown like in the example below
```
---
id: cancel-transportation-order-command-failure-response
name: CancelTransportationOrderCommandFailureResponse
version: 6.0.0
summary: |
  When Node Orderplanning commands an Transportation Order Cancel, 
  this topic is provided in the command, so logistics (Transportation Planning) 
  cap knows to produce the response to this topic
```
this still gets displayed as a single line in the visualiser like in the screenshot below :

![image](https://github.com/event-catalog/eventcatalog/assets/2007116/459304a5-7821-49da-ad67-c301156db72b)

**Comment by boyney123** [comment]
Thank you! And also thanks for fixing.

Changes are now in `@eventcatalog/core@2.0.9`
