### ISSUE TITLE
Schema visualisation does not render correctly when used at the bottom of the page

### ISSUE THREAD

**Issue by debae** [event-catalog/eventcatalog#561]
### Summary
Schema visualisation does not render correctly when used at the bottom of the page

#### Description

Whenever you add the <Schema> component as last one on the page it does not render correctly. So in the index.md I have the following content : 
```
---
id: xxxxxx
name: xxxxxx
version: 1.0.0
summary: |
  xxxxxx
owners:
    - dbaert
badges:
    - content: ACE
      backgroundColor: blue
      textColor: blue
schemaPath: 'schema.avro'
---

### Details
...

<NodeGraph title="Consumer / Producer Diagram" />

<Schema file="schema.avro" />
```
This will render like this :
![image](https://github.com/event-catalog/eventcatalog/assets/2007116/ad08cbcb-fb5d-4c68-92d8-f85eabd58113)

instead of 

![image](https://github.com/event-catalog/eventcatalog/assets/2007116/c1925d0c-4327-4718-b9fc-f126dae1fcc9)

**Comment by andy-g** [comment]
I noticed this if it didn't have a preceding payload code block.

Using the example `OrderConfirmed` event, as soon as I remove the code block and save it, the schema rendering breaks.

### With Code Block:
![image](https://github.com/user-attachments/assets/3afe927a-8beb-4872-a54e-9c887d93605c)

### Once Code block is removed:
![image](https://github.com/user-attachments/assets/f79f0b1d-c3db-4f84-aa4f-93993116588f)

**Comment by debae** [comment]
Maybe some styling that only get's loaded for some other components on which the schema visualiser depends ?

**Comment by boyney123** [comment]
This is now fixed in the latest version of EventCatalog ❤️
