### ISSUE TITLE
Trailing Slash No longer able to be added

### ISSUE THREAD

**Issue by jfevre** [event-catalog/eventcatalog#569]
Hi Im trying to update to v2 from our v1 setup but the option to add the trailing slash added in the below issue no longer looks to be in use can this be implemented into v2
https://github.com/event-catalog/eventcatalog/issues/119

**Comment by boyney123** [comment]
Thanks @jfevre , we have moved over to Astro to power the website, if I expose this to you https://docs.astro.build/en/reference/configuration-reference/#trailingslash would this be useful?

**Comment by jfevre** [comment]
> Thanks @jfevre , we have moved over to Astro to power the website, if I expose this to you https://docs.astro.build/en/reference/configuration-reference/#trailingslash would this be useful?

Yeah that should work perfectly David, Thanks

**Comment by boyney123** [comment]
@jfevre looks like this might already be added https://github.com/event-catalog/eventcatalog/blob/main/astro.config.mjs#L24

Try setting the value to true, did it work?

**Comment by jfevre** [comment]
@boyney123 yeah I already have this set in my config.js from v1 
`trailingSlash: true`
but all of the domains finish without the trailing slash.
![image](https://github.com/event-catalog/eventcatalog/assets/145980981/ad7ed6e1-a696-4f62-b57e-34064529deeb)
This causes a static s3 site its due to the versioning in the URL and the [function](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-add-index.html) needed for the site to work on as a static cloudfront site.
Im trying to alter the function to allow it to still work without it but would allow us to keep the function as recommended if all domains had the trailing /

**Comment by boyney123** [comment]
Cool think I found the issue, will get a release. Once it's done let me know if its fixes your issue.

**Comment by boyney123** [comment]
Fixed in `@eventcatalog/core@2.0.14` and docs added https://www.eventcatalog.dev/docs/api/config#trailingSlash

Let me know if you have any issues.

**Comment by jnixon2** [comment]
I was having the same issue with this, just tried 2.0.14 and redeployed to S3, seems to work, except for when you click the 'View in Visualiser' that does not add the slash to the end.

Also have an issue when viewing open api spec too when deployed via S3, this doesn't work with my Cloudfront function i was using with v1.

**Comment by jfevre** [comment]
@boyney123  Yeah as @jnixon2 reports it looks to work intermittently and some weird behaviours depending on the page you're trying to access
![image](https://github.com/user-attachments/assets/18a7e4b3-28a0-4cf0-9f30-a7d2d72c09a4)
![image](https://github.com/user-attachments/assets/cc21758a-120e-46fe-ad62-45cf4c973373)
