### ISSUE TITLE
Build/dev mode fails if markdown contains comments

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#577]
If your markdown files contain a legit comment like "< ! - - prettier-ignore-start - - >" (spaces to avoid not being rendered) the build and also the dev mode fails with something like:

```
12:38:25 [ERROR] [vite] x Build failed in 9m 58s
[@mdx-js/rollup] Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

**Comment by carlosallexandre** [comment]
Was this fixed with https://github.com/event-catalog/eventcatalog/pull/1029?

**Comment by otbe** [comment]
Removed my workaround and still works :) Thanks
