### ISSUE TITLE
SchemaViewer does not render when deployed to S3

### ISSUE THREAD

**Issue by jnixon2** [event-catalog/eventcatalog#590]
When using the new schema viewer component, this works fine in dev mode locally and renders fine.

However when deployed to S3 the SchemaViewer component doesnt seem to render and i get this error:
<img width="611" alt="image" src="https://github.com/user-attachments/assets/7ffafdfc-8894-497b-a90b-e36aaed641f0">

local:
<img width="934" alt="image" src="https://github.com/user-attachments/assets/67960bb6-8a0b-4cde-8773-93bbfb4867aa">

deployed to S3:
<img width="917" alt="image" src="https://github.com/user-attachments/assets/3d01eaaf-23ee-4911-be9e-d6179a17dbf2">

**Comment by otbe** [comment]
I think its broken as soon as you build the catalog via `npm run build`. Im experiencing the same while just serving the catalog locally.

**Comment by boyney123** [comment]
Interesting, do you have any client side errors in the console?

**Comment by autodidaddict** [comment]
I don't experience this using `npm run dev`, which works fine. I experience this when I deploy to Netlify, the exact same error
![image](https://github.com/user-attachments/assets/0907c387-0df2-4353-9ddf-eeb25b4ea65d)

**Comment by boyney123** [comment]
Should be fixed in @eventcatalog/core@2.0.29, let me know if you still have issue.
