### ISSUE TITLE
Number of Domains owned by a User is hardcoded to 2

### ISSUE THREAD

**Issue by benjwdev** [event-catalog/eventcatalog#609]
The number of Domains owned by a user (# owned domains) is hardcoded to 2, vs. being dynamically calculated.

https://github.com/event-catalog/eventcatalog/blob/6c7cb465e787ea4bb3692268810bd83f0d76c555/src/pages/docs/users/%5Bid%5D/index.astro#L104-L105

<img width="813" alt="Screenshot 2024-07-17 at 12 18 07" src="https://github.com/user-attachments/assets/82a281ef-8c1d-43d1-99b5-b24c8e35a80c">

**Comment by boyney123** [comment]
Fixed this for now removing it, was more work than I thought added support for it. At least it's gone now.

I added a new ticket for a feature to add it #615

**Comment by boyney123** [comment]
Thank you for raising the bug
