### ISSUE TITLE
Domains folder level organization is breaking the rendering

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#626]
- The current version does not allow to have nested folders to separate domains and their other related sub-folders. Eg.:
    - domains
        - Domain-A
            - Services
                - Events / Commands
        - Domain-B
    - This issue also avoids reading domains in subfolders.
    - This attempt to organize everything under the folder structure as above is leading the eventcatalog to render everything under the domains folder, listing ALL messages, services, and domains.
    
This is how I'm trying to organize folders in my project:    
![image](https://github.com/user-attachments/assets/dbc61565-0fca-48a3-9332-2107ab518ef6)

And this is how eventcatalog is rendering:
![image](https://github.com/user-attachments/assets/ec0932b1-1b3c-47c4-8930-04a7e6d9be69)

The only domain in this is list is: `Brands`

**Comment by boyney123** [comment]
Yeah EC v2 only works if they are seperated into the `domains`, `events` and `services` folders at the moment and does not support sub folders (yet). If we get enough traction with this issue or future issues we can look into this

**Comment by jr-araujo** [comment]
Fair enough!
