### ISSUE TITLE
The references of messages requires to inform versions all the time

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#628]
- Every time I need to reference a message in the frontmatter section of a service document (index.md), I need to repeat the **version** property of each message.
    - it could get the latest official version and let it not required, allowing one to decide when that message can be referenced to a previous one.

Here I needed to repeat all the time the `version` property:
![image](https://github.com/user-attachments/assets/d6b762c4-2d09-470c-abbc-86f71b288e8d)

**Comment by boyney123** [comment]
This is now live in EventCatalog 2.4.0! Also default is set to `latest` making the field optional now :)
