### ISSUE TITLE
Member inside within a team is not be bound to a service

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#630]
Once I have a team filled with some people, they are referenced in teams and domains, but each person is not be reflected as owners of services and messages.

Eg.: I have a team called `XPTO` as depicted in the image below:

![image](https://github.com/user-attachments/assets/c9636d1a-21e1-4463-8483-795c4f969ced)

This user is already a member of XPTO team, but as you can see, he is not assumed as owner of services and messages.
![image](https://github.com/user-attachments/assets/055a092b-b5d7-49c9-9425-3998a08e1ecb)

--

The project only assumes the referenced user when I put his name right down below the team name:

![image](https://github.com/user-attachments/assets/8f63f22c-2990-4020-90ea-a72d6bb7c332)

![image](https://github.com/user-attachments/assets/ded98d7f-a3ad-4b86-bcfa-e276c0724bec)

**Comment by boyney123** [comment]
This is now fixed.
