### ISSUE TITLE
Horizontal large content in code blocks make right hand sidebar disappear

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#634]
If you have a code block with a large (horizontal) content it makes the right hand sidebar disappear.

Instead of doing this it should have a max width and display scrollbars at some point. Happens for events and services, most likely for domains as well.

See repro: https://github.com/otbe/eventcatalog-sidebar-repro

<img width="1463" alt="Screenshot 2024-07-19 at 18 33 07" src="https://github.com/user-attachments/assets/4b3d3da5-c531-4ea4-92ce-f3d0ccf97748">

**Comment by boyney123** [comment]
Thanks @jacktomlinson looks like this should now be fixed.
