### ISSUE TITLE
Long(er) summary of events, service, domains make discover page display horizontal scrollbars

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#635]
Repro is here: https://github.com/otbe/eventcatalog-sidebar-repro

<img width="1542" alt="Screenshot 2024-07-19 at 19 08 46" src="https://github.com/user-attachments/assets/0e94135d-ad6a-489e-a16a-293dd8c4661c">

**Comment by boyney123** [comment]
Thanks mate, should be fixed in `2.0.31`
