### ISSUE TITLE
When trying to search a 404 error is raised on console.

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#645]
After opening the application and trying to search for anything, a 404 error was raised on the console, in **developer mode**.

![image](https://github.com/user-attachments/assets/abae40ed-f4ab-4675-96f9-c3ced743b4c9)

![image](https://github.com/user-attachments/assets/89b1caea-7f35-43d8-8da5-2c9ee459c5e7)

**Comment by boyney123** [comment]
We are using `pagefind` which requires a build to get indexed.

Try run `npm run build` to index your system. Sorry I know it's not very intuitive, I might add some docs for this!

**Comment by jr-araujo** [comment]
I just ran this command and reindexed all the files. Even after this, the search is not working for me.

**Comment by boyney123** [comment]
Are you running the latest version of catalog? Only reason I ask is I fixed an issue related to this a couple of weeks ago.

**Comment by jr-araujo** [comment]
This is my eventcatalog.config.js. Due to I configured it to use the latest version of the @eventcatalog/core package, I'm assuming that I'm on the latest version.

```json
{
  "name": "tce-eventcatalog",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "eventcatalog dev",
    "build": "eventcatalog build",
    "start": "eventcatalog start",
    "preview": "eventcatalog preview",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@eventcatalog/core": "latest"
  },
  "devDependencies": {
    "@parcel/watcher": "2.4.1",
    "concurrently": "8.2.2"
  }
}
```
