### ISSUE TITLE
When trailingSlash=true link to changelog is wrong

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#669]
When your catalog uses trailingSlash=true the link generated for the `Changelog` button is wrong.

`View changelogs` link (correct)
`http://localhost:3000/docs/events/InventoryAdjusted/1.0.1/changelog/`

`Changelog` button (incorrect)
`http://localhost:3000/docs/events/InventoryAdjusted/1.0.1/1.0.1/changelog/`

I think this is due to the fact that `View changelogs` builds the full URL and the `Changelog` button only uses a relative one.

**Comment by boyney123** [comment]
Thanks @otbe 

Fixed in `@eventcatalog/core@2.2.3`
