### ISSUE TITLE
Going to /docs/events/MyEventName should redirect to the latest version

### ISSUE THREAD

**Issue by kaplanbora** [event-catalog/eventcatalog#689]
Some of our users like just change the endpoint to go their event's page. But to get the actual page of the event, you have to pass the version as well, like `/docs/events/MyEventName/0.0.1/`. Otherwise, you see the screen below.

<img width="690" alt="image" src="https://github.com/user-attachments/assets/2af28293-7899-4fa9-8f43-47271cc3b3ee">

It would be much better if it would redirect to the latest version instead.

**Comment by boyney123** [comment]
Makes sense to me!

**Comment by boyney123** [comment]
Thanks @carlosallexandre , this is now fixed in `@eventcatalog/core@2.3.2`

**Comment by kaplanbora** [comment]
Thank you for the quick implementation!
