### ISSUE TITLE
Labels in navigation on visualiser page are not truncated correctly for long names

### ISSUE THREAD

**Issue by debae** [event-catalog/eventcatalog#697]
Similar to https://github.com/event-catalog/eventcatalog/issues/550 , if there are very long names in the visualiser this is not displayed correctly.

![image](https://github.com/user-attachments/assets/2d342073-62e4-42ed-b791-98803086e622)

**Comment by debae** [comment]
@boyney123 you can assign this issue to me

**Comment by debae** [comment]
https://github.com/event-catalog/eventcatalog/pull/698

**Comment by boyney123** [comment]
Merged, thank you @debae !
