### ISSUE TITLE
Search bard is not working locally

### ISSUE THREAD

**Issue by jr-araujo** [event-catalog/eventcatalog#699]
# 🚨 Problem
Is there someone with the same issue as me, when trying to search for something locally? What seems strange is that the DEMO in the EC web page, works fine, but locally doesn't.

When I do that, locally, the console showcases to me a 404 error:
![image](https://github.com/user-attachments/assets/8c36ee1a-1119-4289-9a8d-dee5c35f4371)

If you go to the online DEMO: https://demo.eventcatalog.dev/docs/ , you will see that this feature works properly.

# 🎯 Expectations

The **Search bar** must work the same way locally or after a deployment.

**Comment by carlosallexandre** [comment]
Running the build (`npm run build`) and after the preview (`npm run preview`), it works?

*Related [#645](https://github.com/event-catalog/eventcatalog/issues/645).*

**Comment by jr-araujo** [comment]
@carlosallexandre Yup! you're right about the relation this one has with the #645 

I will close this one. We can maintain the previous one, though.

**Comment by jr-araujo** [comment]
The issue was closed because it was repeated.
