### ISSUE TITLE
When specifying a version of a resource, let the user set value to `latest`

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#701]
When you create services and add the sends and receives, or domains and attach services the version needs to be set to a hard coded value.

It would be nice to let the users set the value to `latest` and let EventCatalog just pick the latest version for them.

**Comment by carlosallexandre** [comment]
Could it be the `default` as mentioned [here](https://github.com/event-catalog/eventcatalog/issues/628)?

**Comment by boyney123** [comment]
This is now live in EventCatalog 2.4.0! Also default is set to `latest` making the field optional now :)
