### ISSUE TITLE
Missing lodash.merge tyescript types make build fail

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#734]
In the latest version (2.5.1) the build fails immediately with

```
src/utils/domains/node-graph.ts:4:19 - error ts(7016): Could not find a declaration file for module 'lodash.merge'. '.../eventcatalog/node_modules/lodash.merge/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash.merge` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.merge';`

4 import merge from 'lodash.merge';

```

Just adding `@types/lodash.merge` as devDep makes it work in my local project.

**Comment by boyney123** [comment]
Ah yeah, the project itself has the dependency, but I had to update the create-new-catalog to also include this on new builds.

For builds already out there, I need a way to do this for folks somehow.... need to think about this! Unless anyone has ideas?

**Heres a summary of the issues:**

- when you create a new catalog, the eventcatalog-core is installed, most things are abstracted away here. The project itself requires this package and a few other things (like cross-env, types etc).
- When we add a new package to the project 90% of the time `eventcatalog-core` updates are fine and works. But if its required in the core folder of the catalog, then you have errors like what we see here.

It's like a need a script that runs on build, or start, or new installs for old versions like this one, and check if any deps are missing or not.... not sure!... will think.

**Comment by otbe** [comment]
Same for the new auto diff feature introduced in 2.7.3.
`@types/diff` is missing then.
