### ISSUE TITLE
Mermaid sequence diagram: illegible font size

### ISSUE THREAD

**Issue by gf-mbr** [event-catalog/eventcatalog#744]
The font size used in mermaid sequence diagrams is 2px, so the text is impossible to read.

```html 
<text dy="1em" class="messageText" style="font-family: var(--sans-font); font-size: 2px; font-weight: 400;" alignment-baseline="middle" dominant-baseline="middle" text-anchor="middle" y="112" x="377">Inventory Available</text>
```
See: https://demo.eventcatalog.dev/docs/domains/Orders/0.0.3#order-example-sequence-diagram

**Comment by boyney123** [comment]
Thanks @gf-mbr should be fixed in `2.16.4`
