### ISSUE TITLE
Duplicated service rendering create-eventcatalog template 

### ISSUE THREAD

**Issue by XaaXaaX** [event-catalog/eventcatalog#745]
The default generated catalog has a twice discovery of Inventory Service v0.0.2
<img width="1245" alt="Screenshot 2024-08-30 at 16 16 45" src="https://github.com/user-attachments/assets/b5152b06-6c0e-452d-bb37-9748b3b6bee5">

This is present in visualiser but also docs home page

**Comment by carlosallexandre** [comment]
We need to think about a single source of truth for examples/templates. 

This issue has been fixed here in `core`, but remains in `create-eventcatalog`.
