### ISSUE TITLE
openapi.svg icon does not consider base

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#755]
After updating to 2.6.0 I noticed that the SVG is missing and seems like it does not consider `base`.

<img width="153" alt="Screenshot 2024-09-05 at 19 26 54" src="https://github.com/user-attachments/assets/f9bcb570-711e-433c-a800-0bb9d09892c3">

**Comment by boyney123** [comment]
Fixed in 2.6.1
