### ISSUE TITLE
ISSUE and PULL_REQUEST templates are broken

### ISSUE THREAD

**Issue by IsmaelMartinez** [event-catalog/eventcatalog#767]
# Context 

The issue template shows this, that direct to the same
![image](https://github.com/user-attachments/assets/ccfedab4-aab3-4022-acd5-8a15ec69e051)

The PULL_REQUEST template mentions CONTRIBUTING.md#pull-requests file, but there is not CONTRIBUTING.md file

# Expected

For each of the templates to work and help users provide helpful information about their issue and/or feature request.

**Comment by boyney123** [comment]
Now fixed, thanks for raising.
