### ISSUE TITLE
Nested resources in v2?

### ISSUE THREAD

**Issue by floriankraemer** [event-catalog/eventcatalog#771]
I've read the migration page and it says:

> Resources require a flat structure
> In EventCatalog v1 you could nest your resources for example have your events or services within your domains folder. (Example /domains/services/MyService/index.md)
> 
> This feature **is not currently supported** in version 2.
> 
> Version 2 requires your domains, services and messages (commands, and events) to be in the root directory.

The key here is this:

> **is not currently supported**

Does that mean you plan to support it any time soon? If yes we will wait for it with the migration.

**Comment by carlosallexandre** [comment]
@floriankraemer 
This is indeed planned. There are some adjustments in progress to be made to fully support this.

**Comment by floriankraemer** [comment]
Awesome! Is there any timeline known when this will be ready?

**Comment by boyney123** [comment]
Thanks @carlosallexandre , yeah hopefully end of September for this one! Maybe sooner if I can get round to it. Most of its done on a branch, but I need to update plugins and SDK

**Comment by boyney123** [comment]
For context , convo https://discord.com/channels/918092420338569216/1281539006936649803

**Comment by floriankraemer** [comment]
Awesome, thank you @boyney123. Is there any way to make a donation? I'll ask my company if they are willing to make a donation or donate something myself.

**Comment by boyney123** [comment]
> Awesome, thank you @boyney123. Is there any way to make a donation? I'll ask my company if they are willing to make a donation or donate something myself.

Sounds great! I'm actually waiting for GitHub to review my application to open sponsors for EventCatalog itself. I just pinged them as its been 2/3 weeks and still pending. Once it's done will share the link :)

**Comment by floriankraemer** [comment]
@boyney123 are any news on this feature request, please?

**Comment by boyney123** [comment]
Hey @floriankraemer on the backlog, just focusing on a new plugin at the moment, and then will take a look at this

**Comment by boyney123** [comment]
Working on this at the moment, should be coming very soon @floriankraemer https://github.com/event-catalog/eventcatalog/pull/888

**Comment by boyney123** [comment]
Ok this is live in 2.9.1 @floriankraemer , you can find some docs here https://www.eventcatalog.dev/docs/development/guides/project-structure#nested-resources-recommended

Let us know if you have any problems

**Comment by floriankraemer** [comment]
Awesome, thank you very much @boyney123! I'll review it on Monday at work.
