### ISSUE TITLE
Search does not work in Visualizer

### ISSUE THREAD

**Issue by hvandenb** [event-catalog/eventcatalog#805]
### I tried this:

After you switch to the visualizer and then select anything in the visualizer diagram the search feature stops working. 

### This happened:

You can try to click on the search bar and it does not have the search pop up. Also the hot key x+K does not respond. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Hey @hvandenb thanks for raising this, which version of EventCatalog are you using?

I'm trying it out here, https://demo.eventcatalog.dev/visualiser/domains/Orders/0.0.3 and can't seem to replicate it?

**Comment by boyney123** [comment]
I can't actually replicate this. Feel free to re-open with steps how to replicate. Going to close for now.
