### ISSUE TITLE
Search causing a 404 on `/pagefind/pagefind.js`

### ISSUE THREAD

**Issue by hukhuk** [event-catalog/eventcatalog#811]
### I tried this:

Trying to search for anything using the search. Clicking the search bar causes the search box to open up.

### This happened:

Searching for anything causes the `Searching for x...` to show up
![image](https://github.com/user-attachments/assets/66845472-82a8-4447-9fa9-0238badf43cd)

but nothing is ever shown in the results.
I can see a 404 in the terminal
![image](https://github.com/user-attachments/assets/b85761dd-cd80-48da-8fa0-79922642f716)
as well as the network tab of dev tools
![image](https://github.com/user-attachments/assets/ad7a17cb-5e8c-405b-9200-379954ccd14b)

### Is there a workaround?

Not that I know of.

### Anything else?

This happens to me on a brand new event catalog created with `npx @eventcatalog/create-eventcatalog@latest` and ran with `npm run dev`.
Platform is WSL2 with Ubuntu on Windows.

### EventCatalog Version

@eventcatalog/core@2.7.15

### Node.js Version

v20.17.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by carlosallexandre** [comment]
[Check this](https://www.eventcatalog.dev/docs/development/guides/eventcatalog-search).
[This issue](https://github.com/event-catalog/eventcatalog/issues/645#issuecomment-2260812317) can help.

Tell us if it works for you :pray:

**Comment by hukhuk** [comment]
That worked, thanks. Maybe it could be added to the getting started -instructions as well?
