### ISSUE TITLE
Hyperlinks to Discover pages on Main landing page

### ISSUE THREAD

**Issue by kotapullarao** [event-catalog/eventcatalog#813]
### Use Case

Hello, To improve user experience, It would be great if we have an option to configure or It directly comes with clickable hyperlinks out of the box to Discover pages on new main landing page. For example "/discover/events" or "/discover/domains" directly when you click on the Image or stats as shown in the screenshot below. Thanks!
![image](https://github.com/user-attachments/assets/57fcc199-4099-423d-9ad7-1fdba1bc0154)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thank you mate, sounds good to me.
