### ISSUE TITLE
OpenAPI path tag grouping names not displayed

### ISSUE THREAD

**Issue by kernwig** [event-catalog/eventcatalog#824]
### I tried this:

openapi.yaml file in a service directory contains tags on paths, like this one:

```yaml
  /getPricingFunctions:
    get:
      operationId: GetPricingFunctionsUsecase
      tags:
        - Pricing Functions
      summary: Get all pricing functions filtered by state
      parameters:
        - schema:
            type: string
            default: draft,active,inactive
            description: Comma separated list of states to filter pricing functions by
          required: false
          description: Comma separated list of states to filter pricing functions by
          name: states
          in: query
      responses:
        "200":
          description: Pricing Functions list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PricingFunction"
```

### This happened:

Left-side navigation shows the paths grouped by their tags, but the tag names are not shown - just and empty space:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/65ca4fc3-87c7-4f45-94ca-054e305df143">

### I expected this:

I expect the heading text "Pricing Functions" to show above "Get all pricing functions filtered by state".

A chevron to collapse it would be nice too, but would want it open by default.

### Is there a workaround?

No.

### EventCatalog Version

@eventcatalog/core@2.7.16

### Node.js Version

v20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Hey @kernwig 

2.8.1 is now out with some changes to the OpenAPI viewer thanks to @XaaXaaX .

Let me know if this works for you, if not, please re-open the issue.

Thanks!

**Comment by XaaXaaX** [comment]
just tested  in a catalog and it works as expected

**Comment by kernwig** [comment]
> Hey @kernwig
> 
> 2.8.1 is now out with some changes to the OpenAPI viewer thanks to @XaaXaaX .
> 
> Let me know if this works for you, if not, please re-open the issue.

@boyney123 Hit this problem with v2.8.1: https://github.com/event-catalog/eventcatalog/issues/799

**Comment by kernwig** [comment]
@boyney123 I do build and preview. Viewing services works fine, but when I click on an OpenAPI spec I see a spinner and Chrome reports that the page is not responding. There is no output in the browser console. I tried with two _small_ spec files.

**Comment by boyney123** [comment]
@kernwig do you have an example OpenAPI spec file I can use to replicate the issue?
