### ISSUE TITLE
Events containing "events" in their name fails to be shown in event catalog

### ISSUE THREAD

**Issue by HansMartinJ** [event-catalog/eventcatalog#834]
### I tried this:

created event directory called "foo-bar-events/"

### This happened:

it wasn't shown in event catalog

### I expected this:

for it to be shown

### Is there a workaround?

not have the event contain "events"

### Anything else?

The problem is in `getTargetPath` in `core/scripts/catalog-to-astro-content-directory.js`. More specifically with the split

### EventCatalog Version

2.8.1

### Node.js Version

v22.8.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by devpsk** [comment]
I have a similar situation, look at: https://github.com/event-catalog/eventcatalog/pull/749/files

**Comment by boyney123** [comment]
Hey, thanks for raising this. This should be fixed in 2.9.1, give that ago, and feel free to reopen the issue if you still have problems, with instructions how we can replicate it. Thanks!
