### ISSUE TITLE
Missing event metada in service NodeGraph

### ISSUE THREAD

**Issue by gabrielcolson** [event-catalog/eventcatalog#842]
### I tried this:

I added an event and a service that consumes the event and displays a NodeGraph

### This happened:

On the service page, the event has `Producers` and `Consumers` at 0

### I expected this:

to have `Consumers: 1`

### EventCatalog Version

@eventcatalog/core@2.8.2

### Node.js Version

v20.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by carlosallexandre** [comment]
@gabrielcolson share the markdown files that you define the event and service to us.
