### ISSUE TITLE
Add support for services to consume and produce the same event in Visualiser

### ISSUE THREAD

**Issue by gabrielcolson** [event-catalog/eventcatalog#843]
### Use Case

We have services that consume themselves the events they produce. The same event id is specified in `sends` and `receives`. On the service NodeGraph, the event is only linked by a `publishes event` arrow and misses the `receives event` one. On the event page, the only link is `subscribed by`.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by otbe** [comment]
To add on this: I think it would be nice to support this kind of self referencing basically for all node types. My example would be a flow that documents an aggregate lifecycle (allowed state transitions) and if you have something like a `UserChanged` event which can occur multiple times and it would be nice to see an arrow to itself in this case.

**Comment by DavidMealha-Onfido** [comment]
Found the same issue when trying to represent an event that is both sent and received in the same service.

**Comment by boyney123** [comment]
Thanks makes sense to me to support this. Thanks for raising it @gabrielcolson

**Comment by boyney123** [comment]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/06c9be86-47f3-498c-abf7-669853dc2835">
<img width="1382" alt="image" src="https://github.com/user-attachments/assets/d4ef4bdd-2af9-4925-8a93-9e8cae48f34b">


Working on this now, should be live in the next few days

**Comment by boyney123** [comment]
Ok this should be working in `@eventcatalog/core@2.12.0` now, let me know if you have any issues.

Thanks for the idea @gabrielcolson
