### ISSUE TITLE
Unable to search in discover tab, also unable to click next page

### ISSUE THREAD

**Issue by HansMartinJ** [event-catalog/eventcatalog#847]
### I tried this:

Generated the catalog using generator-asyncapi (5 events,  8 services). 

Went into the discover page and clicked on the search fields of events. 

### This happened:

It successfully shows a preview of all the available events, but when I click on one of them to filter, nothing happens.

### I expected this:

For it to filter based on the even I chose

### Anything else?

This also applies for filtering services and domains as well

Also unable to click next page (even when I had more than 8 services)

generator-asyncapi version: 2.1.1

### EventCatalog Version

2.8.1

### Node.js Version

v22.8.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by HansMartinJ** [comment]
Actually it seems that it fails since we have a function that does some path operations in eventcatalog-config.js, which it is trying to run in the browser. It worked after we wrapped it in a try/catch.

**Comment by gaddam1987** [comment]
This issue can be closed, it becuase of using `path` in eventcatalog-config.js which is needed for asyncapi generator

**Comment by boyney123** [comment]
Thank you for raising the issue @HansMartinJ , and @carlosallexandre I love your fix implementation, using the ENV I think is a good idea here. Thanks for this!
