### ISSUE TITLE
Enable External URL Support for AsyncAPI Files in Services Configuration

### ISSUE THREAD

**Issue by Nayra-Neves** [event-catalog/eventcatalog#848]
### Use Case

I would like to propose an enhancement to the existing configuration of services in the EventCatalog, specifically regarding the integration with AsyncAPI files. Currently, the services property in the eventcatalog.config.api file only accepts local file paths for the AsyncAPI definitions (At least as far as I understand from the documentation and testing). Below is an example of the current configuration structure:

```
[
  '@eventcatalog/generator-asyncapi',
  {
    services: [
      { path: path.join(__dirname, 'asyncapi-files', 'new-uc-service.yml'), id: 'Client Service'},
    ],
    domain: { id: 'clients', name: 'Client', version: '0.0.1' },
    debug: true
  },
],
```
Proposed Enhancement:
I would like to suggest extending this feature to allow referencing external AsyncAPI files via URLs (for example, https://raw.githubusercontent.com/asyncapi/asyncapi/2.0.0/examples/2.0.0/streetlights.yml). This feature would significantly improve collaboration and integration across teams.

### Proposed Solution

**User story suggestion**
**Title:** Allow External URL References for AsyncAPI Files in EventCatalog

**Description:** As an EventCatalog user, I want to reference AsyncAPI files through external URLs, so that different teams can easily collaborate and keep the event documentation always up-to-date without the need to copy files locally.

**Acceptance Criteria:**

- The system should allow the path property in the services configuration to accept external URLs (e.g., files hosted on GitHub, or anyanother public URL, etc.).
- When providing an external URL, EventCatalog should be able to fetch and process the AsyncAPI file just like it does with a local file.
- The system should validate and return a clear error if the provided URL is invalid or inaccessible.

### Implementation Notes

**Possible Implementation Flow:**

1. Detect if the path is a URL.
2. Make the HTTP request to fetch the file.
3. Process the file based on the format (YAML or JSON).
4. Validate the AsyncAPI file to ensure it is correct.
5. Integrate the AsyncAPI file into EventCatalog as is done with local files.
6. Handle errors like invalid or inaccessible URLs.

**Conclusion:**
This approach will allow EventCatalog to be more flexible and enable easier collaboration between teams that manage AsyncAPI files in a decentralized manner, simplifying access to externally hosted files.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by gimmebytes** [comment]
Hello @Nayra-Neves & event-catalog community 👋,

the lack of this feature let to the situation at my former company, that we started creating tooling around syncing/pushing changed/updated spec files from any given repo in the central eventcatalog repo. While this approach worked, it required a lot of tooling around.

So I would also totally opt for having the ability, to link to existing files outside the catalog repo. I only see the challenge, that proper authn/authz needs to be put in place too, because in corporate environments you would never see private spec files sitting on the webs without auth.

What I would be interested in is, how this feature would be different when the event catalog actually would get a real backend, instead of being generator locally @boyney123 ?

If support on this issue is required, we can help ✌️

Cheers,
Marvin

**Comment by XaaXaaX** [comment]
@Nayra-Neves @gimmebytes 
may be this can work to handle the situation https://serverlessfolks.com/automating-eventcatalog-at-scale

The only thing required is add the option for using fromUrl instead of fromFile in @asyncapi/parser if the path starts with http/https 

@boyney123  any idea?

**Comment by boyney123** [comment]
Hey folks,

Yeah totally makes sense to me, I think version one let's support the url (we can work on auth later), if it's a URL then we can use the `fromUrl` as you mentioned @XaaXaaX and if not file as usual. 

Sounds good to me!

@gimmebytes `be different when the event catalog actually would get a real backend` yeah I have been thinking about this more recently too, more about sidecar functionality for eventcatalog for things like notification systems, schema registry (API support) etc.... so watch this space! For now static builds with EventCatalog.

**Comment by boyney123** [comment]
I'm happy to add this should'nt take much I will make a PR and version

**Comment by boyney123** [comment]
Thanks for the suggestion folks, this is now added to @eventcatalog/generator-asyncapi@2.3.0

You can set the `path` value as a URL. This will fetch from the given URL, you can mix this with local files or external urls in the generator.

No auth has been implemented yet, but we can tackle that as a seperate PR if anyone has any issues or ideas :)

**Comment by XaaXaaX** [comment]
> Thanks for the suggestion folks, this is now added to @eventcatalog/generator-asyncapi@2.3.0
> 
> You can set the `path` value as a URL. This will fetch from the given URL, you can mix this with local files or external urls in the generator.
> 
> No auth has been implemented yet, but we can tackle that as a seperate PR if anyone has any issues or ideas :)

He @boyney123 
I was on that but ok , just i was struggling with unit tests and mocking ;)

**Comment by boyney123** [comment]
Docs updated 👍 https://www.eventcatalog.dev/docs/development/plugins/async-api/intro#fetch-asyncapi-files-by-url
