### ISSUE TITLE
Config setting for configuring the Astro outDir

### ISSUE THREAD

**Issue by Sheemap** [event-catalog/eventcatalog#849]
### Use Case

We use EventCatalog in a monorepo, where everything is packaged and stuck into a `dist/{project_path}` dir. This involves running a process and then copying over specific out files/dirs.

Unfortunately, because we cannot customize the path of EventCatalog's dist, when we run our packaging tool, it ends up in `dist/dist`

### Proposed Solution

It would be awesome if we could just specify a custom `outDir` in eventcatalog.config.js. Similar to the other astro settings available, like `trailingSlash`

### Implementation Notes

Id imagine adding the `outDir` follows the same patterns as other astro settings. Accepting a value from eventcatalog.config.js, while having a default for `dist`

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Hey @Sheemap 

Added `outDir` to the catalog in version `@eventcatalog/core@2.11.4`.

https://www.eventcatalog.dev/docs/api/config#outDir

Thanks for raising the issue!

**Comment by boyney123** [comment]
Hey @Sheemap 

Thanks for coming back, ahh yes makes sense. TBH I think this makes sense to me

`outDir: config.outDir ? join(projectDirectory, config.outDir) : join(projectDirectory, 'dist'),`

I can't see why the core would ever need it, and just write to the users catalog makes sense. I will raise a PR for this and clean up the scripts as you said :) thanks for feedback!

**Comment by boyney123** [comment]
OK think I have a fix here #915 will test it out
