### ISSUE TITLE
Event is missing from Service detail page if it is not the most recent version

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#85]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Imagine I have a service `myService` and it subscribes to two events `eventA` and `eventB`.  Both events have versions (lets say for both version 1 and version 2).

If I add `myService` to the list of `consumers` for  `eventA`  version 2 (latest) and for `eventB` version 1, only `eventA`  will be shown in the service overview.

If I navigate to the specific version of `eventB` my service is shown. I think this behaviour is fine for the event view itself but all events should be listed on the service view.

What do you think about it?
<img width="1243" alt="Screenshot 2022-01-19 at 08 28 11" src="https://user-images.githubusercontent.com/3391052/150084102-4df5b1f1-9b0a-4cf5-bf1d-ee9ef11a93b1.png">
<img width="942" alt="Screenshot 2022-01-19 at 08 28 28" src="https://user-images.githubusercontent.com/3391052/150084117-33a66796-f246-40a6-bbda-2287fdd5a637.png">

### Steps to reproduce

https://github.com/otbe/eventcatalog-playground

### Expected behavior

All events are shown in the service overview (that my service subscribes to/publishes).

### Actual behavior

Only the most recent events are shown. If a service subscribes to an old version its not listed in the service overview. 

### Your environment

- EventCatalog version used: 0.0.9

**Comment by boyney123** [comment]
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!
