### ISSUE TITLE
Flow does not respect `latest` for service versioning

### ISSUE THREAD

**Issue by gs-jdudulski** [event-catalog/eventcatalog#854]
### I tried this:

```yaml
- id: Order
  title: Order
  service:
    id: OrderService
    version: latest
```

### This happened:

Service is rendered as step node, instead of Service node.

<img width="167" alt="Screenshot 2024-10-10 at 13 45 05" src="https://github.com/user-attachments/assets/e00af22f-b816-4a80-8fd7-e9e8e7e8ff98">

### I expected this:

Render service node.

### Is there a workaround?

Use explicit version.

<img width="171" alt="Screenshot 2024-10-10 at 13 45 10" src="https://github.com/user-attachments/assets/46685053-aadc-4ba2-9dfd-d9aba3877794">

### EventCatalog Version

2.8.2

### Node.js Version

22.5.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks @carlosallexandre, this should now be fixed in the latest version. Thanks for raising the issue @gs-jdudulski
