### ISSUE TITLE
Resolve external references in json schema files

### ISSUE THREAD

**Issue by jannicke-fjordline** [event-catalog/eventcatalog#893]
### Use Case

It would be really helpful to be able to reference external json schema files, so that we don't need to duplicate a lot of definitions.

I tried referencing a file like this:
```
            "PaymentMethod": {
              "$ref": "./paymentMethod.schema.json"
            }
```
but the JSON Schema viewer doesn't resolve the reference, and looks like this:
![Skjermbilde 2024-10-21 kl  10 35 08](https://github.com/user-attachments/assets/30b54d1a-8329-4393-a539-b848a5914f57)

I would like it to look like this, like when I define PaymentMethod in `definitions` in the same file:
![Skjermbilde 2024-10-21 kl  10 36 44](https://github.com/user-attachments/assets/36bafc29-a7b1-4521-be92-7a0d8681217e)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by jannicke-fjordline** [comment]
@boyney123 But I'm not using any generator, so will this solve my problem then? I'm creating json schemas for events.

**Comment by boyney123** [comment]
Hey @jannicke-fjordline ,

Yeah without the generator then you may need to add them to the Catalog already parsed, unless we add something to do this for folks with some catalog config stuff, but as of today you will have to have a prebuild script or something to parse them into the correct format you want.

**Comment by jannicke-fjordline** [comment]
Okay, I'll look into that then, thanks!

**Comment by boyney123** [comment]
Going to close for now. For folks the generator will handle this https://www.eventcatalog.dev/docs/development/plugins/open-api/intro, with the property `saveParsedSpecFile` (https://www.eventcatalog.dev/docs/development/plugins/open-api/api#saveParsedSpecFile)

If you are not using generator you can parse before you save the file to your catalog. If many people agree we can add this support to EC
