### ISSUE TITLE
Display repository url and language

### ISSUE THREAD

**Issue by jannicke-fjordline** [event-catalog/eventcatalog#897]
### Use Case

The example services, for instance InventoryService, have fields for repository url and language, but they are not displayed anywhere anymore. It would be nice to have them back.
```
repository:
  language: JavaScript
  url: https://github.com/boyney123/pretend-shipping-service
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks for raising this @jannicke-fjordline , should be fixed in 2.11.2. 

You will see this on the right hand sidebar in your docs for your services. You can also add this to your domains and messages if you like.

Thanks!
