### ISSUE TITLE
Support fort .env files for custom components

### ISSUE THREAD

**Issue by jderboven** [event-catalog/eventcatalog#900]
### Use Case

For my customer needs, I have to connect an API and displat data from a private internal service. 

For such issues, I set up a .env file within the components folder, it was working well (copied within the generated astro app) but since the last update, it is no more the case.
Could we have a support for custom .env files within the repository ?

Thank you

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by XaaXaaX** [comment]
@jderboven 
if you expose some sensitive data in the .env file this will be a security hole, why not use runtime environment variables instead of bundling the sensitive data in the bundled asset?

**Comment by jderboven** [comment]
> @jderboven if you expose some sensitive data in the .env file this will be a security hole, why not use runtime environment variables instead of bundling the sensitive data in the bundled asset?

@XaaXaaX actually .env files are not pushed to our remote branches, in the meantime it means via runtime env vars that we should somehow script them, might get cumbersome ? We have to go through some PAT from our ops environment also, that's why we chose .env file to hold those data

**Comment by XaaXaaX** [comment]
Actually the Eventcatalog is on top of astro with a predefined structure, so there is no way to inject extra content to the bundled structure 
Having this 
<img width="336" alt="Screenshot 2024-10-27 at 14 45 29" src="https://github.com/user-attachments/assets/5bfd4641-c900-4856-8ca7-a13fdae1e195">

will result to the following build result
<img width="479" alt="Screenshot 2024-10-27 at 14 46 18" src="https://github.com/user-attachments/assets/31988c29-f69f-4a12-b3f0-7e2fccb752e6">

all this folder structure is EC standard , you can find it here https://github.com/event-catalog/eventcatalog/tree/main/src/pages/docs/%5Btype%5D/%5Bid%5D/%5Bversion%5D

**Comment by jderboven** [comment]
So that means we *have* to go through runtime env vars and there is no way a private .env can be provided ?

**Comment by XaaXaaX** [comment]
@jderboven To the point no there is no way 
Another point is the custom components are bundled at build time to the destination markdown so there will be no folder structure for them.

But as a solution i propose , you can use dotenv-cli and put your .env file in root , 
instead of running npm run build , run dotenv -- npm run build 

This way your custom component will be fed by that env variable and the value will be bundled as part of target page

**Comment by jderboven** [comment]
> @jderboven To the point no there is no way Another point is the custom components are bundled at build time to the destination markdown so there will be no folder structure for them.
> 
> But as a solution i propose , you can use dotenv-cli and put your .env file in root , instead of running npm run build , run dotenv -- npm run build
> 
> This way your custom component will be fed by that env variable and the value will be bundled as part of target page
> 
> I would like to note that Astro is a build time rendered solution and not a server side so there is no way get at runtime the variables but the way is to bundle them
> 
> Gving this response i tried to test the idea and it works , here the BBBBB is the value of env var declared in `.env` file This is generated by `npm run build` command prefixed with dotenv as `dotenv -- npm run build` , i put the `.env` file side of package.json file ( i did not try other places but you can try that )
> 
> <img alt="Screenshot 2024-10-27 at 17 38 12" width="760" src="https://private-user-images.githubusercontent.com/13409925/380514162-8a4d05b0-976d-4f27-a0b4-326ed22e9378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzMzNDIsIm5iZiI6MTczMDI3MzA0MiwicGF0aCI6Ii8xMzQwOTkyNS8zODA1MTQxNjItOGE0ZDA1YjAtOTc2ZC00ZjI3LWEwYjQtMzI2ZWQyMmU5Mzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3MjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTcxMWU5NWRjOWI3YTViYjY2MDE1YjcxMDAxZDU5NTBiNjZiYTQ4NGNiZTEwNGVhODg5N2Y3ZmE0ZTEyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nCI9fThTtRFDYjqnCAHAnrQfV6jQ1DDEO-5iP4MqPPY">

Thanks for the help

**Comment by XaaXaaX** [comment]
@boyney123 
I think this requirement is worth a document page, explaining how the env vars will be bundled at build time and propose this solution

Also a hint to be careful about sensitive info is a nice to have

**Comment by boyney123** [comment]
sounds great to me @XaaXaaX, did you wanna try make a PR for it? Or want me to pick it up?

**Comment by XaaXaaX** [comment]
> sounds great to me @XaaXaaX, did you wanna try make a PR for it? Or want me to pick it up?

@boyney123  i ll raise the PR ;)
