### ISSUE TITLE
Styles not loaded for Schema component if no code is on the page

### ISSUE THREAD

**Issue by boyney123** [event-catalog/eventcatalog#932]
### I tried this:

If you have a page like this:

```
---
id: lightmeasuredmessageavro
version: 1.0.0
name: lightMeasuredMessageAvro
summary: ''
badges: []
schemaPath: schema.avsc
---
## Architecture
<NodeGraph />


## Schema
<Schema file="schema.avsc" title="Message Schema" maxHeight="500" />

```

The UI will render the page like this

<img width="593" alt="image" src="https://github.com/user-attachments/assets/fd935153-df27-46d0-b65d-f716c78f27fb">

The (Schema) component is not rendered as expected.

### This happened:

Broken UI

### I expected this:

<img width="414" alt="image" src="https://github.com/user-attachments/assets/5eed70fe-135a-4c37-89f2-5e73196b8119">

### Is there a workaround?

Force the code block to be rendered

```
---
id: lightmeasuredmessageavro
version: 1.0.0
name: lightMeasuredMessageAvro
summary: ''
badges: []
schemaPath: schema.avsc
---
## Architecture
<NodeGraph />

```
```

## Schema
<Schema file="schema.avsc" title="Message Schema" maxHeight="500" />

```

But it would be nice if we didnt have to hack this

### EventCatalog Version

Latest version

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by TheDiggster13** [comment]
I'm also getting this issue. Please could you expand on your workaround until a fix is generated. As far as I can see the workaround code looks the same as the code that has the issue.

**Comment by boyney123** [comment]
Hey @TheDiggster13 

Work around would be to add an empty code snippet

```
---
id: lightmeasuredmessageavro
version: 1.0.0
name: lightMeasuredMessageAvro
summary: ''
badges: []
schemaPath: schema.avsc
---
## Architecture
<NodeGraph />

Empty code snippet here
```
``

## Schema
<Schema file="schema.avsc" title="Message Schema" maxHeight="500" />

```

**Comment by boyney123** [comment]
@carlosallexandre fixed this @TheDiggster13 in the latest version, if you want to update 👍
