### ISSUE TITLE
Channel information parameters show the wrong fields on the channel detail page

### ISSUE THREAD

**Issue by debae** [event-catalog/eventcatalog#951]
### I tried this:

When you open a channel in de demo of event catalog, for example https://demo.eventcatalog.dev/docs/channels/inventory.%7Benv%7D.events/1.0.0

### This happened:

 You will see the options being shown the description, and the description in the default.

![image](https://github.com/user-attachments/assets/0d8df402-7c79-4207-9e5e-91577e3f68d3)

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Ah thanks, fix going out now
