### ISSUE TITLE
Flow rendering breaks when you enable message simulation

### ISSUE THREAD

**Issue by markallanson** [event-catalog/eventcatalog#955]
### I tried this:

Visit a flow when message simulation is enabled.

### This happened:

The screen briefly showed the flow (flickered), then showed a blank screen

### I expected this:

The flow to render as normal

### Is there a workaround?

Visit any other visualizer and turn off message simulation, then go back to the flow

### Anything else?

This happens if you enable simulation while viewing a flow as well.

### EventCatalog Version

@eventcatalog/core@2.13.1

### Node.js Version

22.9.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks @markallanson this should be fixed in the new release of EventCatalog (coming out today)
