### ISSUE TITLE
Collapse receives/sends/consumes/produces lists of things in Explore section

### ISSUE THREAD

**Issue by otbe** [event-catalog/eventcatalog#956]
### Use Case

When your catalog grows and you have a lot of events, commands, queries the explore section tends to become visually crowded by the pure amount of entries in the Producers/Consumers/Sends/Receives/Services column. Sometimes I have to scroll 2 screen heights to get to the next service/domain.

<img width="583" alt="Screenshot 2024-11-13 at 19 27 09" src="https://github.com/user-attachments/assets/a2d555e1-75ac-434c-8240-fbcda1ec145c">

### Proposed Solution

It would be nice if we could somehow show only X entries and hide the others (only visually) behind a collapsable area or something similar. Im not an UI expert :D

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
ah yeah... ha, makes sense to me!

**Comment by boyney123** [comment]
Thanks @otbe , I added a fix for the services table, to now show something you can collapse if you have over 10 messages in these columns.

**Comment by boyney123** [comment]
Will be released in the next version of Catalog. Let me know how you get on!
