### ISSUE TITLE
A href are not correctly displayed within steps

### ISSUE THREAD

**Issue by jderboven** [event-catalog/eventcatalog#968]
### I tried this:

```
<Steps>
    <Step title="Récupérer le formulaire HTML pour ajouter ou mettre à jour la méthode de paiement">
      <a href="msg_command">link</a>
    </Step>
</Steps>
```

### This happened:

Styles are not applied to my anchor tag, appears as plain old text

### I expected this:

Anchor tags should be underlined and hoverable the way it is everywhere else.

As far as I've seen, the `.not-prose `class is setup and anchors put a `.prose` class

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks for raising this @jderboven , will be fixed in `2.14.2`. Thanks!
