### ISSUE TITLE
Add Support for Microsoft Teams Chat Links with 'teamsChatUrl' in Frontmatter

### ISSUE THREAD

**Issue by SebasRendon12** [event-catalog/eventcatalog#977]
### Use Case

Many organizations and teams use Microsoft Teams as their primary communication tool instead of Slack. Currently, EventCatalog supports Slack integrations, but there is no way to define a teamsChatUrl in the frontmatter for linking Microsoft Teams channels. This limits the usability of EventCatalog for those who rely on Teams for collaboration. Adding this functionality would make EventCatalog more inclusive and flexible for a wider range of users.

### Proposed Solution

Introduce a teamsChatUrl property in the frontmatter, similar to the existing Slack configuration. This would allow users to specify a Microsoft Teams channel link for teams or users. Ideally, when a teamsChatUrl is present, EventCatalog should display an actionable button or link in the UI with the MS Teams icon, enabling users to quickly access the corresponding Teams channel. This feature would make EventCatalog adaptable to organizations using Microsoft Teams without disrupting current Slack functionality.

### Implementation Notes

- Add a teamsChatUrl property in the frontmatter schema.
- Update the UI to dynamically display a "Chat on Teams" button when the teamsChatUrl is provided.
- Ensure this feature works seamlessly alongside existing Slack integrations, allowing users to choose their preferred platform.
- Provide documentation or examples in the README to demonstrate how to configure and use the new teamsChatUrl property.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Sounds great to me, should be simple enough to add, if anyone wants to pick this up, could be a great first issue.
