### ISSUE TITLE
Remove zoom out limitations

### ISSUE THREAD

**Issue by cdavernas** [event-catalog/eventcatalog#990]
### Use Case

When on a very large domain such as mine (250+ events), the current zoom out limitation is very frustrating, as it forbids me to have an overview of my whole topology.

### Proposed Solution

Remove the zoom out limitation, or increase it drastically.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks for raising this @cdavernas , it has been fixed and will be released in our next version (later today)
