### ISSUE TITLE
Support environment at the beginning of the channel

### ISSUE THREAD

**Issue by jsteiml** [event-catalog/eventcatalog#993]
### I tried this:

I used the example from [here](https://www.eventcatalog.dev/docs/development/guides/channels/adding-messages-to-services)
and simply removed `inventory` from the channel id: `- id: inventory.{env}.events` to `- id: {env}.events` which is how all of our topics on Kafka are setup.

### This happened:

an error is received: ```[astro] 21:04:01 [ERROR] [content] bad indentation of a sequence entry```

### I expected this:

I expected it to allow me to use {env}.kafkaTopic 

### EventCatalog Version

2.15.0

### Node.js Version

18

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by carlosallexandre** [comment]
@jsteiml 

Try like this `- id: "{env}.events"` (Quoted as string)

**Comment by jsteiml** [comment]
That worked, thank you!

**Comment by boyney123** [comment]
Great! Thanks @carlosallexandre !
